### ISSUE TITLE
How to make elasticsearch use less ram

### ISSUE THREAD

**Issue by cinetube** [bbilly1/tubearchivist#102]
![Screenshot 2021-12-06 102606](https://user-images.githubusercontent.com/23441775/144787518-fa878c34-e629-463c-91cd-8fde8fd8e465.jpg)

Elasticsearch is using 800mb of RAM. What configuration I need to change so that it uses less ram?

**Comment by bbilly1** [comment]
Please refer to the elasticsearch documentation for any fine turnings or look into docker container memory configurations if you want to configure that. But I'm not sure how successful you'll be due to the nature of elasticsearch heavily utilizing in memory caching.
