### ISSUE TITLE
Trouble with Codecs, videos locked at 720p30

### ISSUE THREAD

**Issue by Brancliff** [bbilly1/tubearchivist#105]
Example video: https://youtu.be/BZE5QZofYGw

I'm running my download format as bestvideo[VCODEC=avc1]+bestaudio[ACODEC=mp4a]/mp4, since it lets videos play in my XUL browser (#83). Videos downloaded with the default 0 download format seem to be fine, but they won't play in my browser.

I'm not sure what codec I'm supposed to use for this - I can watch the YouTube version of that example video just fine in my browser, so I know its hypothetically possible. Stats for Nerds lists the video's codecs as vp9 (303) / opus (251), but if I try to format videos as bestvideo[VCODEC=vp9]+bestaudio[ACODEC=mp4a]/mp4, the video is the same - both copies of the video even have the exact same filesize.

**Comment by bbilly1** [comment]
Please refer to the yt-dlp [documentation](https://github.com/yt-dlp/yt-dlp#format-selection) about the options available to select a format that fits your needs. Additionally I'd also recommend to look into your browser settings to activate or install some of these common media codecs.

**Comment by Brancliff** [comment]
I checked out the yt-dlp documentation page. It listed video codecs such as av01, vp8, vp9, vp9.2, h263, h264, h265, and theora. I tried all of them. For some reason, all 8 of these codecs resulted in a 720p30 video. The filesizes are all the same too, which leads me to wonder if I just got an identical file 8 times.

![2021-12-11 23-27-45 Downloads](https://user-images.githubusercontent.com/22332774/145704241-a61d58cb-4ccf-48c1-b02d-2161da544355.png)

Is there any way to track what codec I'm "supposed" to be using? When I view Stats for Nerds on a YouTube embed, it'll either say vp9 or avc1, but downloading with either one results in a 720p30 video.

**Comment by bbilly1** [comment]
Were you able to find a solution in the documentation of yt-dlp? You can extend the examples there to your liking, and with little bit of tinkering this could be a solution for you:

```shell
yt-dlp "https://youtu.be/BZE5QZofYGw" \
    -f "bestvideo[height=1080][vcodec^=avc1]+bestaudio[acodec^=mp4a]/mp4" \
    --simulate
```

Note the carrot `^` as a *starts with* character so you don't have to write out the whole codec like `avc1.64002a`. This for example will give you (with a fallback to "mp4"):
```
[youtube] BZE5QZofYGw: Downloading webpage
[youtube] BZE5QZofYGw: Downloading android player API JSON
[info] BZE5QZofYGw: Downloading 1 format(s): 299+140
```

which is matches with:
```
ID  EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR     ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
299 mp4   1920x1080   60 │   26.27MiB 4251k https │ avc1.64002a 4251k video only              1080p60, mp4_dash
140 m4a                  │  821.95KiB  129k https │ audio only        mp4a.40.2  129k 44100Hz medium, m4a_dash
```

Or you could also just select the format directly if you already know what you need:
```shell
yt-dlp "https://youtu.be/BZE5QZofYGw" -f "299+140" --simulate
```
and then maybe provide a fall back should these formats not be available for any reason for example like that:
```shell
yt-dlp "https://youtu.be/BZE5QZofYGw" \
    -f "299+140/298+bestaudio[acodec^=mp4]" --simulate
```

Or any combination of the above or more with even additional fallback options as described in the documentation of yt-dlp.

Hope this helps but this is mostly a questions of yt-dlp format selection and your browse's of choice incompatibility with modern media codecs and not necessarily an issue of Tube Archivist.
