### ISSUE TITLE
Feature Request: Allow creation of custom, auto-playing playlists

### ISSUE THREAD

**Issue by mindofbeholder** [bbilly1/tubearchivist#108]
I enjoy using tubearchivist as an ad free way to watch long videos on my phone while i'm cleaning around the house.

I want to be able to create a playlist of downloaded videos that when the first one finishes it goes to the next one and auto plays.

**Comment by bbilly1** [comment]
Yes, autoplay, I've been thinking about that too. Next version will feature a brand new media player with more opportunity in integrate controls like that. 

For user created playlists, the challenge there is going to be to separate between youtube playlists and local playlists, that could be confusing. That will require some ideas on how to implement that from a UI perspective so it's clear what's happening.

**Comment by geekedtv** [comment]
Comment.

**Comment by bbilly1** [comment]
It's on the roadmap, closing this issue to keep the list fresh.

**Comment by greg321321** [comment]
see related issue #590 for user created playlist feature
