### ISSUE TITLE
Exposing it to internet?

### ISSUE THREAD

**Issue by satirovaf** [bbilly1/tubearchivist#11]
Thanks for this amazing script!

I've edited the docker-compose to change the path of the directories, and after running `docker-compose up -d`, all the images are build and started, but I'm not able to access it over the internet on port 8000.

My server has a static IP and all doors open, maybe on compose I need to insert 0.0.0.0:8000 to be able to access it?

**Comment by bbilly1** [comment]
Hi there, opening that up to the internet is not a good idea, there is no authentication, there is limited validation in the forms, potentially CSRF issues and I'm sure, many other potential problems. It's in the [known limitations](https://github.com/bbilly1/tubearchivist#known-limitations) as this is still very early stages and definitely not secure in any kind of sense.

So if you want to access it from the internet, I'd recommend some kind of openvpn/wireguard setup into your network. That's in general a good idea even if the developer claims everything is perfectly secure. :-)
