### ISSUE TITLE
Not downloading full channel

### ISSUE THREAD

**Issue by thisisawesome1994** [bbilly1/tubearchivist#120]
Hi.

Why does tube archivist not download the whole channel? Is there a setting I have overlooked?

I tried setting 50 pages but that didn't solve anything.

Awaiting Your response,

Thisisawesome1994

**Comment by thisisawesome1994** [comment]
Also, could you add proxy support for the Down loading

**Comment by thisisawesome1994** [comment]
And would I be able to "docker stop tubearchivist", move files from drive a to b and edit /etc/fstab to the new drive and reboot in case I want to migrate drive?

**Comment by thisisawesome1994** [comment]
Would you mind creating An emby plugin?

**Comment by bbilly1** [comment]
OK, let's group this together and take it one at a time:

1. Download whole channel is described under [Add to Download Queue](https://github.com/bbilly1/tubearchivist/wiki/Downloads#add-to-download-queue) of the wiki section. There is more interesting things in the wiki and might be a good start.
2. Docker has proxy settings per container already, no need to implement that again on an application level. Refer to the docker documentation for that. There are also dedicated proxy containers that could handle that too.
3. Docker doesn't really care how you have your drives organized, just mount them to the correct folder in the container as described under the volumes section. Docker doesn't have *hidden files*, just volumes.
4. No there is currently no plans to go beyond the web interface. But who knows what the future holds. :-)

**Comment by thisisawesome1994** [comment]
It only adds 10000 video's to download queue.
It is going to take days Just adding 50k video's to queue, then it only adds 10000. Then IT Will scan again after download, and again.

Would be Nice to set limit to queue amount.

**Comment by bbilly1** [comment]
OK, give me some details so I can reproduce that: which channel with over 10k of videos are you adding to download queue? 

and yes, you should expect around 3secs per video to parse the Metadata and validate the urls availability to add it to the queue.

**Comment by thisisawesome1994** [comment]
No. I found out it is probably downloading, but the counter on the webui is reporting 10.000 video in queue.
So, I have 43k video's on queue, but counter on webui is stuck on 10000 and stays there. Even after Many downloads complete. Will have to wait for all of Them to download. 

Guess all problems are solved now, only queue counter should support higher number.

**Comment by thisisawesome1994** [comment]
should it add videos that are downloaded immediately to home?
Because the videos are being downloaded, but not added to the home page.

**Comment by thisisawesome1994** [comment]
on page 19 I have video's from 14 april 2021, while on page 20 I have from 17th of july 2021. On page 1 I have 1st of january 2022.

**Comment by thisisawesome1994** [comment]
I also have videos from 14 february 2021 on page 19

**Comment by thisisawesome1994** [comment]
nevermind, I have found no critical issue here.
