### ISSUE TITLE
Rescan channel banner and video thumbnails

### ISSUE THREAD

**Issue by danmed** [bbilly1/tubearchivist#121]
I messed up during setup and movign data around and my initial channel and first video download are missing the thumbnails / banner..

How do i regrab those?

**Comment by bbilly1** [comment]
There is a [Thumbnail check](https://github.com/bbilly1/tubearchivist/wiki/Settings#thumbnail-check) task just for such occasions.

**Comment by danmed** [comment]
Thank you.. it sorted itself over night.. ! Love this app!
