### ISSUE TITLE
Re-download with new quality settings

### ISSUE THREAD

**Issue by danmed** [bbilly1/tubearchivist#122]
Is there an easy way to redownload all my channels with new quality settings? 

( i was a little naive about how much space i needed :) )

**Comment by bbilly1** [comment]
You'll have to delete it, change the setting and add it back again. You could extract the video ids from the [backup](https://github.com/bbilly1/tubearchivist/wiki/Settings#backup-database) first, so you don't have to find them again. Do a little json parsing to get just the IDs and add them in one go.

**Comment by danmed** [comment]
That;s what i figured.. no big deal.. i'm still archiving so i've not
watched anything yet.
