### ISSUE TITLE
Quality Settings per channel

### ISSUE THREAD

**Issue by danmed** [bbilly1/tubearchivist#123]
Is this something that's even remotely possible?

**Comment by bbilly1** [comment]
Possible yes, but not implemented. But would be useful for an array of different settings.

Do you want to work on that?

**Comment by danmed** [comment]
I would love to be able to, but i've no experience with anything other than PHP i'm afraid...

**Comment by bbilly1** [comment]
Hehe, just checked out your profile and saw some interesting projects and though I'd ask. :-)

**Comment by danmed** [comment]
:) appreciate you checking them out.. they are pretty much all bash or PHP though :)

**Comment by bbilly1** [comment]
we now have basic per channel customization support in v0.1.3. please update. 

closing this issue for now.
