### ISSUE TITLE
Feature Request: Download Live Videos

### ISSUE THREAD

**Issue by Ritter99** [bbilly1/tubearchivist#131]
It would be awesome if we could automatically detect and download live video streams from specific channels in the event the channel marks them as private after they’ve ended.

**Comment by bbilly1** [comment]
Honestly, I don't know how this could be implemented. You'd have to scrape your channels on youtube constantly, waiting for a stream to appear. This will result in a lot of automated requests to youtube, that might get you in trouble. 

But finished live streams will land in your channel subscribtion, so you'll be able to download them then, but yes, not if they aren't available after streaming...

**Comment by bbilly1** [comment]
Sorry, I think we'll have to shelve this idea for now.

**Comment by Nfivez** [comment]
There is always a link for live stream at https://www.youtube.com/channel/id/live

I have personally used cronjobs that check if it is live with yt-dlp without much issue, but can usually be 1 hour. I think yt-dlp and ytarchive(written in go) allows you to wait for a scheduled livestream as well, which can reduce the amount of scraping. I hope this give you a better idea! Feel free to let me know if there is anything I can help with.

![image](https://user-images.githubusercontent.com/72845991/160363695-26e92617-a97d-4d1d-9dc9-73cb2c050ae4.png)
![image](https://user-images.githubusercontent.com/72845991/160363896-aec7f093-b04e-4ef9-a172-2b5905baa1cf.png)

**Comment by bdruth** [comment]
fwiw, and to help others that might be coming here in the future - this is implemented by https://github.com/HoloArchivists/hoshinova - I think they check the channel's RSS feed and then use `ytarchive` behind the scenes once a live stream is detected.

**Comment by bbilly1** [comment]
Cool project, thanks for sharing. This suffers from the same problem, as that is has to constantly poll YT to look for streams.

In the mean time we do have a notification platform: https://members.tubearchivist.com/

This gets realtime notifications from YT directly, including stream announcements, removing the need to constantly poll, so that feature would be feasible to be implemented through that.

**Comment by minding-myown-business** [comment]
Would this be possible for scheduled streams so you don't have to constantly check the channel for any live streams
