### ISSUE TITLE
Enhancement: Use named volumes in docker-compose

### ISSUE THREAD

**Issue by insuusvenerati** [bbilly1/tubearchivist#132]
Using named volumes would add a couple of advantages:

* Keep the cloned repo clean
* No permissions issues (cannot find source for this)
* Easier to backup
* Volume drivers allow use of cloud tech

**Comment by Cycor** [comment]
How is a volume easier to backup?
I always found a local folder structure a lot easier to backup that a volume (which basically is a folder anyways).

And I accidentally removed a volume more than once, never a folder. It would suck to lose all your videos when removing/updating the container.

**Comment by insuusvenerati** [comment]
There are tools / utilities a plenty that back up docker volumes. 

https://github.com/loomchild/volume-backup

The only situation where you would accidentally delete a docker volume would be if you deleted all the containers associated with it, then manually delete the volume. It would be no easier than deleting a folder.

**Comment by insuusvenerati** [comment]
It's also, roughly, considered a security weak point to mount a host volume in a container.

**Comment by Cycor** [comment]
Looking at that backup solution, it just mounts the volume in the container, compresses it, and outputs the compressed file, no different that a normal tar backup.

Like discussed here, bind backup is easier:
https://stackoverflow.com/questions/34357252/docker-data-volume-vs-mounted-host-directory

I was really just looking for a nice backup solution but it seems I'll be stuck with cron jobs and a tar script.

And I can't find anyone saying that local mount is a security risk, so I would like some more info on that.

My primary concern is media and cache, I don't mind that the database is a volume since we get a backup function in the app.
- media because I would like to have access to the video files.
- cache because that folder is used to import existing videos and backup/restore.

**Comment by insuusvenerati** [comment]
From https://docs.docker.com/storage/

```
Bind mounts: Available since the early days of Docker. Bind mounts have limited functionality compared to volumes. When you 
use a bind mount, a file or directory on the host machine is mounted into a container. The file or directory is referenced by its full
 path on the host machine. The file or directory does not need to exist on the Docker host already. It is created on demand if it 
does not yet exist. Bind mounts are very performant, but they rely on the host machine’s filesystem having a specific directory 
structure available. **If you are developing new Docker applications, consider using named volumes instead. You can’t use 
Docker CLI commands to directly manage bind mounts.**
```

Some use cases for bind mounts:

- Sharing configuration files from the host machine to containers. This is how Docker provides DNS resolution to containers by default, by mounting /etc/resolv.conf from the host machine into each container.

- Sharing source code or build artifacts between a development environment on the Docker host and a container. For instance, you may mount a Maven target/ directory into a container, and each time you build the Maven project on the Docker host, the container gets access to the rebuilt artifacts.

From https://docs.docker.com/storage/volumes/:

```
Volumes are the preferred mechanism for persisting data generated by and used by Docker containers. While bind mounts are dependent on the directory structure and OS of the host machine, volumes are completely managed by Docker. Volumes have several advantages over bind mounts:

    Volumes are easier to back up or migrate than bind mounts.
    You can manage volumes using Docker CLI commands or the Docker API.
    Volumes work on both Linux and Windows containers.
    Volumes can be more safely shared among multiple containers.
    Volume drivers let you store volumes on remote hosts or cloud providers, to encrypt the contents of volumes, or to add other functionality.
    New volumes can have their content pre-populated by a container.
    Volumes on Docker Desktop have much higher performance than bind mounts from Mac and Windows hosts.

In addition, volumes are often a better choice than persisting data in a container’s writable layer, because a volume does not increase the size of the containers using it, and the volume’s contents exist outside the lifecycle of a given container.
```

**Comment by insuusvenerati** [comment]
As discussed in Discord, the main point of the change is simply to get a local setup going with as little config changes and hurdles as possible. Mainly, using named volumes avoids the issue with elasticsearch permissions.

**Comment by bbilly1** [comment]
I think this makes sense, easy enough if people want to change it should they want to move a volume to a different drive or so, but it will all work without manual changes, with one single docker-compose up command.
