### ISSUE TITLE
[Feature Request] Integrate old search URL feature into new search page

### ISSUE THREAD

**Issue by n8detar** [bbilly1/tubearchivist#134]
It would be great if the old style of search, which I use to integrate into Flame (A self-hosted homepage/new tab page), `https://tubearchivist.example.com/?search=This%20is%20a%20test` was integrated into the new search page. For example, if I put `https://tubearchivist.example.com/search/?search=This%20is%20a%20test` it would fill `This is a test` into the new style of search.

**Comment by bbilly1** [comment]
Parse the query string and use that to populate the search box? Good idea, that would be quite straight forward to do. 

Btw, for the time being, the original query parser is still in place if you want continue using that for now, your example `https://tubearchivist.example.com/?search=This%20is%20a%20test` still works as before, I have just removed the now redundant form.

**Comment by bbilly1** [comment]
Closing this for now, it's on the roadmap, we'll revisit with search page improvements.
