### ISSUE TITLE
[Feature Request] Add support to cast videos directly to cast compatible devices.

### ISSUE THREAD

**Issue by n8detar** [bbilly1/tubearchivist#135]
Right now in order to play any Tube Archivist content on a cast-supported device, you have to cast the whole browser screen or use third-party tools to cast the video by right-clicking and on the video and copying the video address, and pasting it into the tool. It would be great to be able to directly cast the video to Chromecasts/cast enabled devices/Android TVs from Tube Archivist. Cast supports directly playing a video as long as you send it a direct address to the video e.x. `https://tubearchivist.example.com/media/video_title.mp4` and the video format is `MP4` (Which is what TA uses), `HLS` or `M(PEG)-DASH`.

I don't know how easy it would be to implement this but this would make it easier to use Tube Archivist on TVs.

**Comment by bbilly1** [comment]
Hmm, very nice idea, did a bit of research and that looks very promising. Sadly I personally don't have any cast device, so this would be difficult to work on for me. Is there somebody out there who'd like to help with that? Please hit me up on our Discord!

**Comment by n8detar** [comment]
In the future, if the podcast mode is implemented being able to cast that would also be a good feature to have.

**Comment by bbilly1** [comment]
created an issue, implemented the functionality, that's the dream! :-)
