### ISSUE TITLE
Import degrades mkv files

### ISSUE THREAD

**Issue by Cycor** [bbilly1/tubearchivist#138]
When importing mkv files you are using
ffmpeg -i file.mkv file.mp4
this causes ffmpeg to recode the mkv instead of just remuxing it, reducing the quality.

I usually use this line to remux, but you might need to check if the codec can be used in an mp4 container
`ffmpeg -i input.mkv -movflags +faststart -c:v copy -c:a copy -c:s copy -c:t copy ouput.mp4`

**Comment by bbilly1** [comment]
Yeah, you are right, I just used the catch all command to convert any file to mp4, not just mkv. What would be a good solution for that? Some kind of a mapping of file extension to optimal ffmpeg command? This way, even when ingesting media files with different file types, the mapping could look up the optimal command. Do you mind looking into it? Find the ideal ffmpeg command for the different filetypes?

**Comment by Cycor** [comment]
sure, i already got a python script that uses ffprobe to figure out what needs to be converted and what can be remuxed so I can cobble something together from that.

**Comment by bbilly1** [comment]
Well... A PR would be even better! :-) I think you have found the `ManualImport` class, and the ffmpeg command here, call with subprocess? https://github.com/bbilly1/tubearchivist/blob/edc9f3fe156127a68b321f3595078e19a3f6c7af/tubearchivist/home/src/reindex.py#L558 

So I was thinking to have an additional method for that class that takes the filename, looks at the file ending and returns the optimal ffmpeg command to be called. Or what do you think?

**Comment by Cycor** [comment]
https://gist.github.com/Cycor/e6e2a1c4e2d907bf7b1a552b7a417472

this is the script i'm using atm, it's still a work in progrss but for yt-dlp downloads it works fine.
I got the original read_video_info from another project so it contains a lot of unused stuff.

**Comment by bbilly1** [comment]
OK, I think we should focus on supporting conversion for three file types: mkv, webm, mov, maybe wmv? I don't know, but why not? So basically we just need the appropriate ffmpeg command that can convert each of these file types to standard mp4. Then we mention in the wiki, which filetypes are supported, and if people have something wired, they can still convert it them self's and ingest the mp4.

Otherwise this will get out of hand quickly. :-)

**Comment by Cycor** [comment]
ffmpeg is insanely good, so I would just let it do it's thing, allow all known types, my script doesn't really look at the source except for if a recode or remux is needed, if it is needed it does a standard x264 conversion (hardware accelerated in my case but not needed) otherwise a copy, that works on all ffmpeg supported types, we just need to check the exitcode and result filesize to be sure if it worked.

**Comment by bbilly1** [comment]
OK, sounds good, looking forward to your implementation! :-)

**Comment by bbilly1** [comment]
@Cycor Were you able to look at this one? Just to make sure we don't end up doing double the work. :-)

**Comment by Cycor** [comment]
I'll try to push something this weekend, haven't gotten a lot of free time last week, got most of the code ready and I'm doing a bunch of test runs with weird codecs to get the best settings to keep the quality/subtitles/metadata etc and copy the data if possible.

**Comment by bbilly1** [comment]
closing this for now, we can revisit that again when improving the offline import functionality.

**Comment by bbilly1** [comment]
Same state as mentioned in the [wiki](https://github.com/tubearchivist/tubearchivist/wiki/Settings#manual-media-files-import). I'm probably not going to extend the manual import any further for the foreseeable future. If you have any specific requirements, convert the videos first with your preferred settings. Or if you feel strongly about it, make a PR.
