### ISSUE TITLE
[Feature request] Unlisted video status

### ISSUE THREAD

**Issue by Cycor** [bbilly1/tubearchivist#139]
I download a lot of videos from Patreon, and those are always unlisted.
I would like that flag to be shown or searchable so I know what videos are more important ( and more likely to be removed ).
This can be combined with a deleted flag if on a rescan the video can't be found anymore (maybe this already exists).

Maybe even have a special playlist/filter per channel with all the unlisted/deleted videos.

I know this is a very niche request so I don't expect much, but can't hurt to ask.

**Comment by pairofcrocs** [comment]
I agree.

A flag for unlisted, deleted, and privated videos would be great.

**Comment by bbilly1** [comment]
There could also be something like google search, where they have *site:* keywords for example. So there could be some similar keywords too. You can already see it on the video page, when the video is still no youtube you'll get the link to it, if not, it's *deactivated* there, but there is currently no filter or anything like that. 

Videos, will get deactivated with the rescan scheduled task, if they aren't available anymore. So there is currently no way to differentiate between reasons, it's just active True or False.

**Comment by bbilly1** [comment]
closing this for now, it's on the roadmap.
