### ISSUE TITLE
[Feature Request] Add setting for content directory

### ISSUE THREAD

**Issue by Roshy10** [bbilly1/tubearchivist#145]
### What
I'd like to be able to specify a directory other than the root of the one being passed into the contaner's `/youtube` volume. Either through the settings menu or as an environment variable

### Why
The reason for this is I have an NFS share as a docker volume and there's no way to specify another directory since you must pass the entire volume into the container (not sure why but it is what it is).

**Comment by Roshy10** [comment]
I'm happy to have a go implementing this when I get some time if it helps

**Comment by bbilly1** [comment]
I don't think I understand the problem you are describing, you might have to clarify for me. 

As far as I can tell from the [docker docs](https://docs.docker.com/storage/volumes/#create-a-service-which-creates-an-nfs-volume) you should be able to create your NFS volume from anywhere to anywhere? At least when you create the volumes with docker like that. You should also be able to create the volumes on your host system with fstab or similar if you need more flexibility, and then just mount a subfolder as a regular volume into the container at /youtube?

**Comment by thisisawesome1994** [comment]
this is exactly what I posted about, but you deleted my post saying you dont reinvent raid or so

**Comment by Roshy10** [comment]
You can indeed attach it to any NFS share, but only to the root of that share due to limitations of the filesystem. For example if I have an NFS share `Archive` containing a `youtube` directory, I can only pass `Archive/` to a container, and it's up to the container to know to go into the `youtube` (or whatever you call it) directory.

It's also true that it could be mounted into the host through fstab combined with regular volume mapping, but that couples the container to the specific host it's running on, requires root privileges, and adds more complexity to configuration than just writing a docker compose file. It also means that if there's an error with the NFS connection restarting the container is insufficient and the host must be restarted or the share manually remounted.

I also think given the nature of an archiving application it won't be uncommon for people to want to mount network shares easily

**Comment by bbilly1** [comment]
OK, had some time to look into that. The issue with that is, that the /youtube folder is not just relevant for Tube Archivist but also to Nginx, as the media files will get served from [there](https://github.com/bbilly1/tubearchivist/blob/master/docker_assets/nginx.conf). Then for django that variable also gets stored in redis (ta:config) from this [template](https://github.com/bbilly1/tubearchivist/blob/master/tubearchivist/home/config.json) which is then used to build the media urls for the interface.

Honestly I'm very reluctant to further complicate that by also making it configurable, and that only for such an edge case which already has a multiple working solutions and workarounds. This is what Docker is for, abstracting the filesystem, network mounts all these things so this application can focus on the task at hand. 

Maybe raise this issue with the Docker team?

I hope I'm not coming off unreasonable and you can see where I'm coming from.
