### ISSUE TITLE
Does update solve my problem

### ISSUE THREAD

**Issue by thisisawesome1994** [bbilly1/tubearchivist#152]
Hi,

Does updating to 0.1.0 solve my problem?
If so, how do I update?

My problem?

I am on 0.0.9 and scanning takes 5 days, but last time I checked, it said 129345 of 134986 video's scanned.

Now I check again, and not a single video is on the download queue, and the scanning is gone.

Please tell me how to proceed.

**Comment by bbilly1** [comment]
with all things like that, we'll always need docker logs to see what's happening. I think I need a message somewhere about that so I don't need to ask about that every time...

as mentioned before, definitely better to do this maybe one channel at a time.

also I wouldn't be surprised if you are getting blocked by now. I'm sure YouTube dedects 100k+ automated requests and will do something about that at some point.

**Comment by thisisawesome1994** [comment]
That is why I want proxy support

**Comment by bbilly1** [comment]
> That is why I want proxy support

I'm not going to repeat my self.

1. I don't appreciate your condescending tone, please consider where you are and be nice.
2. If you aren't prepared to do the bare minimum to help to improve the project, don't open any issues.

**Comment by thisisawesome1994** [comment]
I dont know where to find the logs, and plan on uploading the logs later when I find them.
I am just very busy, and have been trying to download the whole 130k+ videos 3 times already, which took over 1,5 weeks total, without effect. Thank you for you informative solution to download per channel first.

In the long run, using proxies seems a must when people have large collections.

And sorry for being a bit angry. 

The program just took 1,5 weeks of my enthousiasm, without effect..

I am downloading per channel now, and it is working great.
