### ISSUE TITLE
Maximal number of pages

### ISSUE THREAD

**Issue by chowchow-love** [bbilly1/tubearchivist#156]
I have downloaded a lot of videos.  On home page, each page shows 24 videos and the total page number of pages is 834. if i download more videos, the total number of pages remains the same (834), the older videos are no longer indexed and displayed. when you click page 834, you will get the following error (the older videos are still present on hard drive). I guess it is somehow related to database?

KeyError at /
'_source'
Request Method:    GET
Request URL:    https://archivist.mydomain/?page=834
Django Version:    4.0.1
Exception Type:    KeyError
Exception Value:    
'_source'
Exception Location:    /app/./home/src/searching.py, line 106, in hit_cleanup
Python Executable:    /usr/local/bin/uwsgi
Python Version:    3.10.1
Python Path:    
['/app',
 '.',
 '',
 '/usr/local/lib/python310.zip',
 '/usr/local/lib/python3.10',
 '/usr/local/lib/python3.10/lib-dynload',
 '/usr/local/lib/python3.10/site-packages']
Server time:    Sat, 22 Jan 2022 07:09:20 +0000

**Comment by bbilly1** [comment]
Thank you for also opening an issue here, after discord, helps to keep things together. 
 
So, I'm pretty sure, the documents still get indexed and your videos are available in the channel pages and from search, that his is just a pagination link builder issue. Can you verify for me, how many videos do you have indexed?

- Access your docker container:
`docker exec -it tubearchivist bash`

- From within your container, show total count of videos:
`curl $ES_URL/ta_video/_count?pretty -u elastic:$ELASTIC_PASSWORD`

This should then show if there is a discrepancy with the total page numbers.

**Comment by chowchow-love** [comment]
this is the output:
{
  "count" : 16553,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  }
}

on the home page, the total page numbers are 834 but page 834 is not working. thus total number of videos are 24x833=19992

**Comment by chowchow-love** [comment]
and you are also correct: the videos do show up in the channels page

**Comment by Code-Slave** [comment]
it indexes fine. all my vids are there just the paginantion is broken

heres debug output

`

hit | {'error': {'caused_by': {'caused_by': {'reason': 'Result window is too large, '                                                  'from + size must be less '                                                  'than or equal to: [10000] '                                                  'but was [10008]. See the '                                                  'scroll api for a more '                                                  'efficient way to request '                                                  'large data sets. This limit '                                                  'can be set by changing the '                                                  '[index.max_result_window] '                                                  'index level setting.',                                        'type': 'illegal_argument_exception'},                          'reason': 'Result window is too large, from + size '                                    'must be less than or equal to: [10000] but '                                    'was [10008]. See the scroll api for a more '                                    'efficient way to request large data sets. '                                    'This limit can be set by changing the '                                    '[index.max_result_window] index level '                                    'setting.',                          'type': 'illegal_argument_exception'},            'failed_shards': [{'index': 'ta_video',                               'node': 'l1ln5gcDTnuI3CtVeQCtlw',                               'reason': {'reason': 'Result window is too '                                                    'large, from + size must be '                                                    'less than or equal to: '                                                    '[10000] but was [10008]. '                                                    'See the scroll api for a '                                                    'more efficient way to '                                                    'request large data sets. '                                                    'This limit can be set by '                                                    'changing the '                                                    '[index.max_result_window] '                                                    'index level setting.',                                          'type': 'illegal_argument_exception'},                               'shard': 0}],            'grouped': True,            'phase': 'query',            'reason': 'all shards failed',            'root_cause': [{'reason': 'Result window is too large, from + size '                                      'must be less than or equal to: [10000] '                                      'but was [10008]. See the scroll api for '                                      'a more efficient way to request large '                                      'data sets. This limit can be set by '                                      'changing the [index.max_result_window] '                                      'index level setting.',                            'type': 'illegal_argument_exception'}],            'type': 'search_phase_execution_exception'},  'status': 400}
-- | --


`

**Comment by bbilly1** [comment]
I'm tempted to accept that. Who would want to click through 830+ pages to find a specific video. That's what the search is for, or the channel and playlist pages. Additionally the sort options will work fine, you for example could just sort descending to look at the 10000 oldest videos. 

So this would mean that the recent videos page is limited to 10000 videos, that's already kind of implied in *recent*. Obviously the pagination error for the very last page will need fixing, could even be that if you have more than 10000 videos, there is a little indicator, and a better word for *last*.

Any thoughts?

**Comment by chowchow-love** [comment]
I think it is very reasonable. Maybe there should be a note below the pages numbers on home page to say so. Thank you so much for this wonderful program! I really appreciate it!

**Comment by Code-Slave** [comment]
once some filtering etc are in sure. as you said. the error needs tio be caught but im not scrolling 823 pages

**Comment by bbilly1** [comment]
That's merged now in v0.1.1.
