### ISSUE TITLE
Write thumbnail to separate file

### ISSUE THREAD

**Issue by pawelmalak** [bbilly1/tubearchivist#157]
Is there an option to write video thumbnail to separate image file?

Image embeded with `--embed-thumbnail` is usually in low quality (480x270 here):
```bash
Stream #0:2: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 480x270 [SAR 1:1 DAR 16:9], 90k tbr, 90k tbn, 90k tbc (attached pic)
```

You can pass `--write-thumbnail --convert-thumbnail jpg` to yt-dlp to save thumbnail in the best quality (e.g. 1280x720) to separate file and to convert it to the specific format.

Would it be possible to add support for custom yt-dlp options or at least an option to save thumbnails instead of embedding them?

**Comment by bbilly1** [comment]
You can find your jpg video thumbnails in the /cache/videos folder, channel and playlist artwork are there too. The thumbnail saved will be the best quality available. That's also the thumbnail used in the interface.

Tube Archivist doesn't use the embeded thumbnail, that's optional and for archival purpose or for those people who want to use the media files in a different media server.
