### ISSUE TITLE
Add feature: Total space in use

### ISSUE THREAD

**Issue by thisisawesome1994** [bbilly1/tubearchivist#158]
Hi,

It would be nice to have a counter for the total space in use by video's.
Preferably at the left or right top of tubearchivist.

If anyone else likes this, please comment below.

**Comment by thisisawesome1994** [comment]
Would also be Nice to have video's in multiple HDD's, so I dont have to use RAID.

So if one HDD is full, it saves on next HDD

**Comment by bbilly1** [comment]
Disk storage is hardware monitoring, that's not what this project is about. There are lot's of OS builtin or dedicated tools out there for that.

And this project is definitely not going to reinvent raid.
