### ISSUE TITLE
About that

### ISSUE THREAD

**Issue by thisisawesome1994** [bbilly1/tubearchivist#160]
I was talking about library management, like in sonarr and radarr.
I am not talking about raid.

btw, where is my post?

**Comment by thisisawesome1994** [comment]
i want to speciffy which youtube channel goes to which harddrive

**Comment by bbilly1** [comment]
I closed your issue, it's still there. I gave the reason, that's a filesystem or OS feature that already exists and doesn't need to be reimplemented on an application level. 

please stop messing with me and please don't open any further issues on this profile.
