### ISSUE TITLE
Auto-ignore videos to download by keyword

### ISSUE THREAD

**Issue by hugalafutro** [bbilly1/tubearchivist#163]
I think it'd be cool if we could define a list of keywords to auto-ignore videos by keyword. Such as "#shorts" or "compilation". LEt me know what you think.

**Comment by bbilly1** [comment]
I think this will only get you so far: For example the shorts, this will depend on that keyword to be in the title or somewhere, there is no category or tag or anything that gets extracted by yt-dlp to guarantee that you can actually ignore all shorts. A quick look at my feed, some channels will add it, some won't, some will have a tag, some won't. 

So a text based, maybe slightly normalized to lowercase or similar, could work on the title and will catch it if it's actually there.

Thinking of it, yt-dlp should extract hash tag links, e.g. https://www.youtube.com/hashtag/shorts, that would be an effective way to then auto ignore! Or maybe a combination of both?

**Comment by hugalafutro** [comment]
Yep exactly something like that, the channels I d/l use #short or #shorts hashtags, but the "Compilation" usually isn't hashtag. Compilation doesn't make sense since I already have all the vids, and many of the shorts are previews or teasers of upcoming videos which I will eventually have too.

Perhaps auto-ignoring is too much if it filters wrong video as the titles change over time (ie way back at the start of the channels there were no hashtags etc), maybe just exclude it from auto d/l?

**Comment by bbilly1** [comment]
Well, auto dl is just a schedule that runs the same thing as when you actually click the button. But I really like the idea if yt-dlp could extract hash tags, that would be very effective and will make sure that it will actually catch what you want to. Let me look into it, if I can write an rudimentary extractor for it and then I'll see if I can raise an issue with them.

**Comment by bbilly1** [comment]
Thanks for the input, it's on the roadmap, closing this here to keep the list fresh.

**Comment by KerbinCenturion** [comment]
I would like to revive op's suggestion
