### ISSUE TITLE
Metadata for Jellyfin

### ISSUE THREAD

**Issue by AKDub** [bbilly1/tubearchivist#165]
I watch YouTube through Plex & Jellyfin (unfortunately both are pretty flakey for this purpose), but I was wondering if you could write an nfo file and save a video image poster in a way that its picked up by Jellyfin, making it much nicer to use on streaming devices.

I presume channel art etc could be done further down the road if this was ever picked up as a feature?

**Comment by bbilly1** [comment]
That's exactly why I created this project, to have something better than Plex, Emby, Jellyfin that's more flexible and can better adapt to the different structure and database requirements that a YouTube archival project has compared to movies and tv shows of these other media servers.

There have been quite a few mentions about that before: #50, #74, #38 with some more details why this is not a priority and not part of the scope of this project, for now at least. 

Also, @yellowspaced created that: https://github.com/yellowspaced/tubearchivist-metadata-export/, you might want to take a look at that.

Additionally, when you embed thumbnail and metadata into the video file, emby at least will be able to read those and correctly display the video.

**Comment by monik3r** [comment]
Just in case it's useful for anyone else: Here's a little script I made to extract thumbnails for Jellyfin (Jellyfin wasn't seeing the embedded thumbnails) https://gist.github.com/monik3r/131e2aaf72853b286f6a039a2ef37fd9

**Comment by snailwaffles** [comment]
I have started work on a jellyfin plugin to pull the metadata and images from the tube archivist api. https://github.com/snailwaffles/jellyfin-tubearchivist-metadata-plugin the experience will not be as rich as the tube archivist one, but it's still useful if you want to watch something on a tv using the jellyfin app for example
