### ISSUE TITLE
How to set trusted origins for a domain name

### ISSUE THREAD

**Issue by stefanorossiti** [bbilly1/tubearchivist#166]
Since the last container update, I get this error while trying to connect to connect to tubearchivist from a domain name (it used to work before). It also still works when connecting with the internal IP.

This is the message I get after trying to log in:

Forbidden (Origin checking failed - https://my.domain.com does not match any trusted origins.): /login/

The cause is clear, but I don't know how to set a trusted origin. Reading the documentation, I didn't find any ENVIRONMENT parameter for docker-compose or a configuration file do edit.

**Comment by bbilly1** [comment]
Which container update are you talking about? From v0.0.9 to v0.1.0? Or are you talking about the unstable builds?

**Comment by stefanorossiti** [comment]
I am using the tag: latest
So I suppose its 0.0.9 to 0.1.0

9 feb 2022 02:49:20 Simon ***@***.***>:

**Comment by bbilly1** [comment]
I can't seem to think what caused that issue. There is currently no limit on the allowed hosts set in django. https://github.com/bbilly1/tubearchivist/blob/5b37bd059cb35dbbc64260ef2ea49f010604fbd2/tubearchivist/config/settings.py#L33 So I assume that your proxy might not be forwarding some headers or something like that?

That's going to be close to impossible to debug without reproducing your setup. Somewhere on Discord somebody had issues because the reverse proxy wasn't setting the `X-Forwarded-For` and `X-Forwarded-Proto` headers. Maybe you are facing a similar problem?

**Comment by stefanorossiti** [comment]
Uhm... ok that's strange. I have others applications (for example nextcloud) that have no problem, and I didn't change any settings from when it was working. But I will look into it just to be sure. 

Meanwhile, this is the whole error message:

```
Help

Reason given for failure:

    Origin checking failed - https://my.domain.com does not match any trusted origins.
    

In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django’s CSRF mechanism has not been used correctly. For POST forms, you need to ensure:

    Your browser is accepting cookies.
    The view function passes a request to the template’s [render](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render) method.
    In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
    If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
    The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.

You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.
```

**Comment by bbilly1** [comment]
Yes, all of these things are implemented, correctly... I think... :-)

Nextcloud handles that by passing a `trusted_domains` array in *config.php* which will set the correct headers which in turn will get picked up and forwarded by the proxy in front of it.

But, I'm not sure why it worked for you in the first place before.

**Comment by Cycor** [comment]
I had the same problems with haproxy, I needed to add these headers to haproxy, maybe the same for your reverse proxy

# add X-FORWARDED-FOR
option forwardfor
# add X-Forwarded-Proto
http-request set-header X-Forwarded-Proto https if { ssl_fc }
