### ISSUE TITLE
Re-download a deleted video

### ISSUE THREAD

**Issue by Extarys** [bbilly1/tubearchivist#173]
I was playing with the yt-dlp settings and downloaded a video to test. I then deleted it. Ever since the deleted video doesn't show in the download page, even after removing and re-adding the channel.

Is there a way to redownload a previously deleted video without deleting all TubeArchivist files and start over? I'm presuming there is an entry in a database somewhere with that video ID being ignored or something...

**Comment by bbilly1** [comment]
Yes, Tube Archivist won't re-download a video you already have, even if you add it to the queue again. 

You can download a video from the dedicated [video page](https://github.com/bbilly1/tubearchivist/wiki/Video). Or a [filesystem rescan](https://github.com/bbilly1/tubearchivist/wiki/Settings#rescan-filesystem) will catch these differences as well.

**Comment by Extarys** [comment]
Thank you I'll retest this next time I make a test ;)
