### ISSUE TITLE
add setting to save info.json from ytdlp

### ISSUE THREAD

**Issue by Code-Slave** [bbilly1/tubearchivist#177]
Would be nice to be able to archive the info.json ytdlp supports and that media server plugins can read

**Comment by bbilly1** [comment]
I see you didn't see the FAQ yet, please take a look: https://github.com/bbilly1/tubearchivist/wiki/FAQ

There you can also see where the priorities are. I think that scope is ambitious enough as it is. 

Thank you for your understanding and I hope we don't have to revisit that topic again for the time being.
