### ISSUE TITLE
Wrong timing after processing subtitles

### ISSUE THREAD

**Issue by a-carvallo** [bbilly1/tubearchivist#180]
Hi, first, thank you for this project I was looking for something like that but none of the other existing projects were this advanced or had all the features this one have.

Regarding features, the recently added subtitles one seems to misbehave in some cases (see attached `input.txt`) when a line is the same in multiple cues (each cue having multiple lines) timings get messed up (see `parsed.txt`, which is just `input.txt` after being processed by `SubtitleParser.process()`).

From what I can see the issue happens here:
https://github.com/bbilly1/tubearchivist/blob/70506ad8f613a84bc826acf8bc4f3f2e161cc412/tubearchivist/home/src/index/video.py#L194-L211

Maybe it shouldn't compare individual lines but only each cue as a whole ?

[input.txt](https://github.com/bbilly1/tubearchivist/files/8119248/input.txt) (Such pattern can easily happen for the lyrics of a music video)
[parsed.txt](https://github.com/bbilly1/tubearchivist/files/8119250/parsed.txt)

**Comment by bbilly1** [comment]
that fixed is now published in v0.1.3. please update.
