### ISSUE TITLE
support for other video platforms

### ISSUE THREAD

**Issue by alphaonion** [bbilly1/tubearchivist#185]
lbry/odyssey, bitchute, rumble, etc.  Im currently using podgrab using rss to grab other platforms but it would be great to have an all in one solution.
thank you for creating this great piece of software :)

**Comment by bbilly1** [comment]
Check out the [FAQ](https://github.com/bbilly1/tubearchivist/wiki/FAQ): There are currently no plans to extend this project beyond YouTube, but who knows what the future holds. :-)

**Comment by danielyrovas** [comment]
LBRY integration definitely would be awesome.

**Comment by badmotorfinger** [comment]
Just wanted to add that **yt-dlp** already supports downloading channels from platforms such as BitChute, Vimeo + many others.
