### ISSUE TITLE
playlist only shows and download 50 titels

### ISSUE THREAD

**Issue by Serph91P** [bbilly1/tubearchivist#187]
Hey so have this strange issue where there are only 50 videos downloaded for a playlist. 
This playlist has 126Videos in it, so why are there only 50 downloaded?
This is the playlist Iam talking about: https://www.youtube.com/playlist?list=PLN39y5i_H0FlcSAUQ3k1pOZxoBMBusc8L
But basically it is with all the playlist/channels I am subscribed to.
If you need anything else from my side dont hesitate to ask.
Had a look at the wiki but found nothing about it.

**Comment by bbilly1** [comment]
That is working as intended: If you want to download the whole playlist as is now, add it to the [download queue](https://github.com/bbilly1/tubearchivist/wiki/Downloads#add-to-download-queue).
If you want to monitor the playlist to look for new videos, [subscribe](https://github.com/bbilly1/tubearchivist/wiki/Playlists) to the playlist which looks at the top [50 videos](https://github.com/bbilly1/tubearchivist/wiki/Settings#subscriptions). 

Or, of course, you can do both as well.
