### ISSUE TITLE
Can we use ffmpeg with a gpu?

### ISSUE THREAD

**Issue by kiwimato** [bbilly1/tubearchivist#190]
Hello,

Really awesome tool here, I'm curious if it's already possible to use ffmpeg + gpu for encoding?
If not I'd be interested in trying to implement it.

Cheers!

**Comment by kiwimato** [comment]
good to know, I wasn't aware of it, then I believe you :) thanks for the fast answer.

**Comment by bbilly1** [comment]
Hey, there is lot's of things to work on! I'd really appreciate the help. Please reach out on Discord if you are interested, so we can coordinate. :-)

**Comment by lyra56k** [comment]
@bbilly1, I just dispatched an import of over 500 videos, many of which are an hour long. I came to the issues here hoping this already got answered and I found this thread. Is there any way I could quickly change the ffmpeg args to utilize a GPU? If not, I can try to help with ffmpeg but I'm not experienced enough to contribute the code for this.
