### ISSUE TITLE
Find playlist button does nothing?

### ISSUE THREAD

**Issue by Serph91P** [bbilly1/tubearchivist#191]
When I click this button it starts scanning for playlists and states a number like 0 of 400. But when it finishes I don't really know what it did. On Show playlist are still the same playlists that have been downloaded or added by myself. So what does this button do?

**Comment by bbilly1** [comment]
From the [wiki](https://github.com/bbilly1/tubearchivist/wiki/Channels#channel-detail):
```
The button Find Playlists will go out to youtube and look for playlists belonging to this channel and index all with at least one video downloaded. [...]
```
and
```
The button Show Playlists will go to the playlists page and filter the list to only show playlists from this channel.
```

Or can you see any errors in the logs that would indicate this is doing nothing?

**Comment by Serph91P** [comment]
> From the [wiki](https://github.com/bbilly1/tubearchivist/wiki/Channels#channel-detail):
> 
> ```
> The button Find Playlists will go out to youtube and look for playlists belonging to this channel and index all with at least one video downloaded. [...]
> ```
> 
> and
> 
> ```
> The button Show Playlists will go to the playlists page and filter the list to only show playlists from this channel.
> ```
> 
> Or can you see any errors in the logs that would indicate this is doing nothing?

Oh okay, now I know that. I always thought that it would look for the playlist of the channel and then show it under show playlist. So I have to look for playlists or videos I want from a channel myself? There is no way to tell TA to fetch all and I can say which I want?

**Comment by bbilly1** [comment]
> Oh okay, now I know that.

So reading the wiki should be considered *minimal effort* before opening any issue in any project for that matter. 

> I always thought that it would look for the playlist of the channel and then show it under show playlist.

Yes, that's exactly what it does.
