### ISSUE TITLE
CSRF error logging in with reverse proxy

### ISSUE THREAD

**Issue by a-jackson** [bbilly1/tubearchivist#192]
I've just set up Tube Archivist using the docker-compose, it works great using the exposed port. I then tried to add it to Traefik on a subdomain with https and the login page loads fine but on logging in I get an error.

```
Forbidden (403)

CSRF verification failed. Request aborted.

More information is available with DEBUG=True.
```

I tried setting the environment variable DEBUG=True but did not get more information so I'm not sure what that is referring to?
There's no information in the docker logs either. I'm not very familiar with Django and Python so don't really know where to look.

Is there some config I'm missing? Is this unsupported at the moment.  Is there something that can help diagnose this?

**Comment by a-jackson** [comment]
Traefik is setting all these headers already. I'm still getting the same error.

**Comment by a-jackson** [comment]
I was able to turn on DEBUG and now have the cause. `Origin checking failed - null does not match any trusted origins.` Seems the browser is setting the Origin header to null the login post. 

This led me to that Traefik was setting `referrer-policy: no-referrer` and therefore the login POST set Origin: null which causes the above error. 

I have removed that setting from Traefik and now login is working as expected.

**Comment by bbilly1** [comment]
Very nice! Thanks for looking into it. At some point this will have to be done properly by passing a host name where the interface should be reachable. But this will break peoples installations, so, even though unavoidable, I'm a bit hesitant.
