### ISSUE TITLE
Feature Request: Button to Rescan for Missing Videos

### ISSUE THREAD

**Issue by Marthisdil** [bbilly1/tubearchivist#201]
Stuff happens occasionally.  Would be nice to have on the download tab a button to click to search for missing videos (for subscribed/not subscribed).  Would be able to pull full video list, compare to whats downloaded, and queue anything missing.

Rescan Subscriptions doesn't see to pull the full video list - just check for new videos from the most recent dated downloaded video.

**Comment by bbilly1** [comment]
you can set the channel page size in the settings to define how many videos you want to look back. or set it to 0 (zero) to scan the whole. 

that's not ideal, check out the mention jn the wiki about that.

**Comment by Marthisdil** [comment]
> you can set the channel page size in the settings to define how many videos you want to look back. or set it to 0 (zero) to scan the whole.
> 
> that's not ideal, check out the mention in the wiki about that.

totally understand it's not ideal...but if you're missing, say, some random older videos (for some reason) after downloading a whole channel, it's not a bad thing to scan the whole channel again looking for videos that have been missed.

also, another example - say for some reason the channel has a high thruput (i.e. a lot of videos being put on it), and you've not had TA up and running for some time (for whatever reason).  You come back, start up TA, and want it to go out and grab all the missing videos (even those missing beyond the initial 50 (by default)).  If you change the page setting on settings, sure, scanning subscriptions will scan all channels for missing/new files.  But then, that applies to ALL channels....not just the high traffic ones.

Sure, you could go in, change the default from 50, to 0, click rescan subs, let it do its thing, then edit the settings to change it back from 0 to 50 i guess....but thats essentially the same as having a button that someone could click (Search Channels for Missing Videos), perhaps even with a warning confirmation about how long it will take, and be done with it without having to change settings twice.  User Convenience type of thing.

**Comment by bbilly1** [comment]
Look like all of these things you can already accomplish quite easily. You can also add the url to any channel you suspect with missing videos to the download form again, even if you rescan your subscriptions once a week, with a reasonable channel page size, you should be able to cover any edge cases you are describing. 

I appreciate the thinking you put into this, from an development and UI perspective, to covering such edge cases the usefulness needs to outweigh the additional complexity, both from the perspective of adding additional buttons and forms to the UI and the code to accomplish that functionality in the application.

Thanks for putting in the time to help improve this application, I hope you can understand my thinking.
