### ISSUE TITLE
Feature Request: Ability to change order of queued downloads

### ISSUE THREAD

**Issue by Marthisdil** [bbilly1/tubearchivist#202]
Being able to move to top, or bottom att the least would be helpful.  Free repositioning via drag and drop would be nice too.

Being able to click and change a priority (low, normal, high) with the downloader grabbing things in high > normal > low order would be good.  Being able to set a priority on a per-channel basis and having the system tag any queued downloads with the priority would be a bonus

**Comment by bbilly1** [comment]
I don't think you want to handle this one by one, that's going to be tedious. you already have the download now button to give a video priority. 

download queue should be set and forget, let Tube Archivist do its thing without you having to do anything. I don't think I'd make this any more complicated than that.

**Comment by Marthisdil** [comment]
Can understand about the single queue entry move...but the remainder of the request may be valid...being able to set a priority for certain channels to get stuff first would still be nice.

**Comment by bbilly1** [comment]
The queue is ordered from the time you added the video to it. So if you want to download some channels with priority, add them first.

This goes in the same direction as my previous comment, the added complexity needs to outweigh the benefit. 

Thanks for your input, I hope you can understand.
