### ISSUE TITLE
Download progress box disappears 

### ISSUE THREAD

**Issue by fromnack** [bbilly1/tubearchivist#210]
Hi there

Sorry if I've not done this right, I've never submitted a bug report on Github before! 

Running on the latest version on Unraid. 

The download progress box disappears randomly, but downloads are still going. It comes and goes intermittently with nothing specific bringing it back, sometimes a refresh or changing pages brings it back. 

Let me know if you need more info!

**Comment by ainsey11** [comment]
This appears to happen when the file takes longer than the message expiry in redis

I'm experimenting putting in a UI box to show that the file move is ongoing, something a little like this:

![image](https://user-images.githubusercontent.com/6608275/162634552-e5d9d120-a8cf-4631-baec-58bc329686a8.png)

**Comment by ainsey11** [comment]
PR has been updated ready for review.
