### ISSUE TITLE
[Bug] Server Error (500) when trying to open Tube Archivist

### ISSUE THREAD

**Issue by obuwunkunubi** [bbilly1/tubearchivist#212]
I recently updated to the latest version v0.1.3 and I have been unable to access any part of the website. At first the container for TA didn't even want to start due to me still using an outdated (7.14.1) version of elasticsearch, but I fixed that by updating from docker.elastic.co/elasticsearch/elasticsearch:7.14.1 to bbilly1/tubearchivist-es:latest. Now the TA container starts, but all I get when trying to access it is Server Error (500). I am running the Docker containers on Unraid.

```
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [stats.view_count] in order to sort on","index_uuid":"ihJMyDAGTEusVTbX-MEsCA","index":"ta_video"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"ta_video","node":"ilfpx13tQBGTqKc0DczunQ","reason":{"type":"query_shard_exception","reason":"No mapping found for [stats.view_count] in order to sort on","index_uuid":"ihJMyDAGTEusVTbX-MEsCA","index":"ta_video"}}]},"status":400}
[pid: 30|app: 0|req: 1/1] 10.10.10.40 () {46 vars in 5721 bytes} [Fri Apr 8 04:13:59 2022] GET / => generated 145 bytes in 398 msecs (HTTP/1.1 500) 7 headers in 233 bytes (1 switches on core 0)
[pid: 30|app: 0|req: 2/2] 10.10.10.40 () {46 vars in 5688 bytes} [Fri Apr 8 04:14:00 2022] GET /favicon.ico => generated 179 bytes in 5 msecs (HTTP/1.1 404) 7 headers in 213 bytes (1 switches on core 0)
```

**Comment by bbilly1** [comment]
Can you try to reset the user config by deleting the dumb.rdb file from your redis volume mount? then restart all. you'll have to go back to the settings page and reconfigure things. let me know if that fixes it.

Then the _real_ fix would be to set all these mappings explicitly.

**Comment by obuwunkunubi** [comment]
Deleting the file and restarting seems to have worked. The videos were missing, so it tried using the "Restore from backup" function in settings. The videos show up now and everything seems to be working, except the "video-thumb" thumbnail images form most of the videos are missing. Is there any way to get those back?

**Comment by bbilly1** [comment]
You can click on "rescan filesystem" on your settings page to validate all your videos and thumbnails.

**Comment by obuwunkunubi** [comment]
That worked, the video thumbnails are back now and everything seems to be working again. Thanks for the help!
