### ISSUE TITLE
Download speed limit changes don't take effect unless container is restarted

### ISSUE THREAD

**Issue by ainsey11** [bbilly1/tubearchivist#216]
I set a download speed limit to 1000 (1MB/S) as per the tip in the settings page:

![image](https://user-images.githubusercontent.com/6608275/162596612-b55339aa-88cc-4217-9151-4bc02dd9145e.png)

I then initiated a download of a video and saw my WAN usage increase to 6MB/S :

![image](https://user-images.githubusercontent.com/6608275/162596606-b0489f4b-0b25-4a3b-ab1f-fd3be0cb8078.png)

However, when I restarted the container and re-initiated the download, it behaved as expected:

![image](https://user-images.githubusercontent.com/6608275/162596637-9e50e654-daa1-4de7-a547-0378970236ac.png)

if I then increase the setting to:
![image](https://user-images.githubusercontent.com/6608275/162596656-4f26b096-69ec-48ca-b67d-39ce31ecdf37.png)

it still remains at the 1000kb/s setting from before:

![image](https://user-images.githubusercontent.com/6608275/162596663-bc2a12f5-dc81-46e1-b0b5-3e54bbc5eb93.png)

**Comment by bbilly1** [comment]
Thank you for your detailed issue and initial debugging, very much appreciated! :-)

However i wasn't able to reproduce it. Setting the speed limit worked for me without restarting the container. 

Few thoughts:
- You can't change the speed on a runnig download task. These values get read once when you click "start download queue" or "download now".
‐ Is it possible that there is a unit coversion issue? Between what you see on your WAN and TA? Not sure, I'll have to take a look at it. But that shouldn't matter for the status message on the downloads page.

**Comment by ainsey11** [comment]
@bbilly1 - I suspect it's the first item - I'd clicked the start download and then tried changing the values, so looks like that is what has happened here, then when re-starting the container it must be restarting the download job with the updated setting rather than continuing with the old job settings (makes sense) 

So appears it does in fact work as designed and was just a little unclear to me as to when they take effect in the application itself

**Comment by ainsey11** [comment]
I've just raised a PR ^ to tweak the wording slightly just to make it friendlier to end users, hopefully you don't mind!

Cheers

**Comment by bbilly1** [comment]
Excellent, thanks for taking care of that! 

I'm always looking for help, if you are interested? Please reach out on Discord, opportunities to shine are abundant! :-)

**Comment by ainsey11** [comment]
No worries!

Sure thing - I'll join and say hello! - my python and djano skills leave a bit to be desired but I'm fairly clued up on js - I'd quite like to work on some bits like prometheus exporters for us folks who like grafana integrations, so would be good to have a chat :D 

Will mark this issue as closed as it's working as expected - speak to you soon!
