### ISSUE TITLE
Home page pagination limit

### ISSUE THREAD

**Issue by PhuriousGeorge** [bbilly1/tubearchivist#221]
I'm assuming this is known, but I didn't see it recorded anywhere.  There appears to be a limitation on the pagination of the home screen.

Firstly, if I click last page (page 834), I get a 500 error

Secondly, if I go to page 833, the oldest video it shows is from Aug 2019 (sorted desc by upload date).  If I change that sort to asc, I only get videos as new as 2016.

**Comment by bbilly1** [comment]
Pagination in deed builds links for up to 10k results: https://github.com/bbilly1/tubearchivist/wiki#general-navigation

That's just the link building, all is there in the channel pages, playlists or from search.

And yes, the last page, there is in deed a silly `>` that should be a `>=` error. Thanks for pointing it out.

**Comment by PhuriousGeorge** [comment]
Doh, I missed the 10k limit comment.  Good call.
