### ISSUE TITLE
Manual media import not available

### ISSUE THREAD

**Issue by kajatak** [bbilly1/tubearchivist#24]
Not really sure what I'm doing wrong here, but the manual import still says "Coming soon". I've tried removing and re-creating the containers, re-downloading the code form GitHub but nothing seems to help. What am I overlooking?

**Comment by bbilly1** [comment]
That looks like you are running on an old version. On a previous version I messed up the docker tagging, maybe that's the issue. 

1. Check that in your docker-compose file you have set `bbilly1/tubearchivist:latest` as your image. So when you pull you should get the newest version. 
2. It's a good idea to run `docker system prune -a` from time to time to delete unused images or old versions of containers.
3. It that doesn't solve it, when you run `docker images` you will see all the images you have and you can delete the old version manually from there with `docker rmi <your image ID>`. This will force docker to download the latest image next time you run `docker-compose pull`.

**Comment by kajatak** [comment]
`bbilly1/tubearchivist:latest` was already set correctly so I thought it would pull the correct image, but seems that pruning all the images and re-downloading them did the trick. It probably just skipped that for some reason. Thanks, and now onward to the next problem :)

Seems that every time when I go to import a file it'll fail (see log below), and what I gather looking at the files themselves it seems that they do get consumed but the actual video file is not - for the most part - being moved, just 50-100 KB or so. All the metadata shows up correctly in the web UI, just 00:00 length and unworking video, since the video is actually not there. What's weird is that sometimes despite failing in the log the file actually does get moved and does work the way it should. All the files are .mp4.

```
tubearchivist      | [2021-09-21 00:16:22,079: INFO/MainProcess] Task home.tasks.run_manual_import[3009a218-c1b9-4ff2-865c-eb7da45ae698] received
tubearchivist      | [2021-09-21 00:16:22,081: WARNING/ForkPoolWorker-2] starting media file import
tubearchivist      | [2021-09-21 00:16:22,081: WARNING/ForkPoolWorker-2] 
tubearchivist      | 
tubearchivist      | [2021-09-21 00:16:22,374: WARNING/ForkPoolWorker-2] get video data for JZRYzWE0Ya0
tubearchivist      | [2021-09-21 00:16:22,375: WARNING/ForkPoolWorker-2] 
tubearchivist      | 
tubearchivist      | [2021-09-21 00:16:32,045: WARNING/ForkPoolWorker-2] processing with ffmpeg: Pattaya Jomtien Beach on Sunday, April 2021 Thailand-(2160p25)-JZRYzWE0Ya0
tubearchivist      | [2021-09-21 00:16:32,046: WARNING/ForkPoolWorker-2] 
tubearchivist      | 
tubearchivist      | frame=    1 fps=0.0 q=28.0 Lsize=      60kB time=00:00:00.00 bitrate=6291384.6kbits/s speed=0.000361x    
tubearchivist      | [2021-09-21 00:16:32,478: WARNING/ForkPoolWorker-2] get video data for JZRYzWE0Ya0
tubearchivist      | [2021-09-21 00:16:32,479: WARNING/ForkPoolWorker-2] 
tubearchivist      | 
tubearchivist      | [2021-09-21 00:16:34,111: ERROR/ForkPoolWorker-2] Task home.tasks.run_manual_import[3009a218-c1b9-4ff2-865c-eb7da45ae698] raised unexpected: FileNotFoundError(2, 'No such file or directory')
tubearchivist      | Traceback (most recent call last):
tubearchivist      |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
tubearchivist      |     R = retval = fun(*args, **kwargs)
tubearchivist      |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
tubearchivist      |     return self.run(*args, **kwargs)
tubearchivist      |   File "/app/home/tasks.py", line 89, in run_manual_import
tubearchivist      |     import_handler.process_import()
tubearchivist      |   File "/app/home/src/reindex.py", line 425, in process_import
tubearchivist      |     os.remove(json_path)
tubearchivist      | FileNotFoundError: [Errno 2] No such file or directory: '/cache/import/Pattaya Jomtien Beach on Sunday, April 2021 Thailand-(2160p25)-JZRYzWE0Ya0.info.json'
```

I tried to just rename the original video and upload that to the correct directory but that didn't help. Any ideas?

**Comment by bbilly1** [comment]
I'm glad somebody is testing this out! :-)

Can you give me the exact filename of the media file, and the exact filename of the json file you are trying to import? So I can recreate it my self. It looks like it extracts the video ID correctly from the json file but somehow building the path is not working.

If you already have an mp4 file, ffmpeg shouldn't get invoked, so that's strange too...

**Comment by kajatak** [comment]
The filenames of one failed file are
```
Pattaya Jomtien Beach on Sunday, April 2021 Thailand-(2160p25)-JZRYzWE0Ya0.info.json
Pattaya Jomtien Beach on Sunday, April 2021 Thailand-(2160p25)-JZRYzWE0Ya0.mp4
```
This is from ytdl using filename format of ``%(title).200s-(%(height)sp%(fps).0d)-%(id)s.%(ext)s``, however I did try just renaming (another video) file simply as ``Waiting-(2160p50)-nEN_hDioY2A.ext`` and it's still failing in the same way, so I'm not sure if the filename has much to do with it. Also tried one without rounds brackets just in case, but it made no difference.

**Comment by bbilly1** [comment]
Hmm, that works without issue for me. Not sure what's happening if I can't reproduce the error...

- So you are putting the files directly into cache/import? There is no additional subfolder there?
- Can you verify that the json file has a key called 'id' with the correct matching value?
- What operating system is docker running on?
- You said it shows up in the interface, but with broken media file. Is the media file still in cache/download?

**Comment by kajatak** [comment]
> So you are putting the files directly into cache/import? There is no additional subfolder there?

Yes, all the files are directly in that directory.

> Can you verify that the json file has a key called 'id' with the correct matching value?

It does, and like I said some of the files do actually work - most with the same "FileNotFoundError: [Errno 2] No such file or directory:" error, but I even managed to get one uploaded without any errors at all. But even some of these files that do error out show up and work correctly.

> What operating system is docker running on?

Ubuntu Server 20.04.3 LTS that's up-to-date. It's virtualized through Proxmox.

> You said it shows up in the interface, but with broken media file. Is the media file still in cache/download?

That directory is empty. The files are actually moved to the correct youtube/channel directory, but the file size of the videos that do not work ranges between 50-100 KB or so.

**Comment by bbilly1** [comment]
OK, I'm at a loss. I can't seem to be able to reproduce it. I'll keep looking but for the moment, that's the best I can do.

**Comment by kajatak** [comment]
Thanks for the help anyway, I guess I'll just wipe the whole thing and start from the beginning to see if that would solve it.
