### ISSUE TITLE
Scanning of subscriptions

### ISSUE THREAD

**Issue by ClementNgZiQian** [bbilly1/tubearchivist#27]
Currently, the current channel page size (default=50) is the number of videos scanned from the newest backwards, however if I just started to archive a new channel, it would probably mean that 50 is insufficient. Instead of manually changing the value to something else, is it possible to instead let it scan for the latest 50 **not** downloaded videos?

**Comment by bbilly1** [comment]
The "add to download" button on the download page also takes a channel ID. That's for if you want to archive all videos of a channel, no matter the channel size. 

Then the subscriptions is for if you also want to archive every future video published by that channel. So for an initial download, add the channel ID to the download queue but also subscribe to the channel, so every future video published will get added to the queue once you rescan.

A higher amount than 50 for the channel page will slow things down drastically. Yt-dlp extracts 50 videos per page, so for every additional page that yt-dlp needs to extract, it will take that much longer to go through.

**Comment by ClementNgZiQian** [comment]
I have tried the `Add to download queue` option and inputted a url in the form `https://https://www.youtube.com/channel/channelname` but it throws a `server error (500)`.

**Comment by bbilly1** [comment]
Make sure you add the Channel ID, a 24 character alpha numeric string and not the username. Username are not unique, any user can have multiple channels. For example _UCrUL8K81R4VBzm-KOYwrcxQ_ or the corresponding URL will work too.

I need to do some better error handling there...

**Comment by ClementNgZiQian** [comment]
Thanks, using the ID instead did the trick, although it did take some time finding the unique ID. On a side note, under the download format, does `bestvideo[height<=1080]+bestaudio/best[height<=1080]` mean `bestvideo[height<=1080]+bestaudio` or `best[height<=1080]` works for `best audio and max video height of 1080p`?

**Comment by bbilly1** [comment]
Nice! 
The formats are just examples, you can use whatever you want. So yes, the `/` is like an _or_ character, and the `+` is for downloading different streams separately and mixing them together. This allows you to select different quality settings for different streams. Maybe audio quality is important to you so you can select `bestaudio` for that but for video 720p is fine and you care more about filesizes so you could select `bestvideo[height<=720]` for that. Then the `/` is if the previous formats are not available for some reason, then yt-dlp will use that as a fallback.

Of course, the [yt-dlp documentation](https://github.com/yt-dlp/yt-dlp#format-selection) has much more examples and better explanations as I ever could.

**Comment by ClementNgZiQian** [comment]
Hi, thanks for the reply, the reason for asking was because I tried using `best[height<=1080]` but it resulted in a 720p download instead. I have tried this on with the pip install of yt-dlp on my pc and it also results in the same 720p download instead of 1080p download. Idk if this is an issue with yt-dlp, or if I'm using it incorrectly, if its the former I would suggest that you can leave the option as `bestvideo[height<=1080]+bestaudio` until they fix it just in case others experience the same issue.

**Comment by bbilly1** [comment]
yt-dlp doesn't just look at the height to define what's "best". You can look into [sorting formats](https://github.com/yt-dlp/yt-dlp#sorting-formats) for more details but that's outside of the scope here. What it looks like, if you want to get 1080p videos, use the provided example: `bestvideo[height<=1080]+bestaudio/best[height<=1080]` this will work for all youtube videos where there is actually a 1080p version available.

Default of Tube Archivist is the same as default of yt-dlp, which is best quality, anything else, is what you have set and can change freely.

**Comment by ClementNgZiQian** [comment]
I see, thanks a lot!
