### ISSUE TITLE
How can I donate?

### ISSUE THREAD

**Issue by pairofcrocs** [bbilly1/tubearchivist#29]
Not being a technical person I can't donate my time, however, I'd love to be a monthly sponsor of this project.

Would you be willing to set up the Sponsor program so that I can help out :)

Keep up the awesome work!

**Comment by bbilly1** [comment]
Wow, thanks a lot, I'm very honored by your kind words.
* If you want to buy me a coffee, I have setup a [paypal.me](paypal.me/bbilly1) link.
* If you want to buy me a coffee every month, I tried to setup a [supporter link](https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-03770005GR991451KMFGVPMQ) on paypal. 

But in any case, please no pressure!

A note about contributing for a non technical person: There are many ways to help, yes code, fixes and patches are one, but for example spelling and grammar issues, translations (in the future hopefully), installation instructions for other platforms... Or just testing out the new releases, look at the release notes and try out the new features mentioned there and see if they all work as expected and then open an issue if you see that anything doesn't work. That's all very useful for this project and for any open source project for that matter. 

Thank you for your support!

**Comment by pairofcrocs** [comment]
I'm really excited to see where this project goes!

I have created an unraid template that will be published on the app store shortly. This will most likely increase the pull requests quite substantially.

I also added your donation link as well :)

**Comment by bbilly1** [comment]
Thank you very much for your support! I have added a [Donate section](https://github.com/bbilly1/tubearchivist#donate) in the readme to future proof the links.
