### ISSUE TITLE
Not a directory error when encountering macOS thumbnail files.

### ISSUE THREAD

**Issue by Mcharlsto** [bbilly1/tubearchivist#30]
Rescanning channels crashes if the download path has been accessed from the macOS Finder, which leaves behind .DS_Store and ._filename thumbnail files, among others.

It should be a pretty simple fix, if you add an exemption for OS temp files from the check.
This gitignore file should be useful for figuring out what files are created - [https://github.com/github/gitignore/blob/master/Global/macOS.gitignore](https://github.com/github/gitignore/blob/master/Global/macOS.gitignore)

Log below:
`[2021-09-24 16:04:05,714: ERROR/ForkPoolWorker-4] Task home.tasks.update_subscribed[e0197cb6-a19f-4f27-b6e4-1481c344944b] raised unexpected: NotADirectoryError(20, 'Not a directory')`

`Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
R = retval = fun(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
return self.run(*args, **kwargs)
File "/app/home/tasks.py", line 29, in update_subscribed
missing_videos = channel_handler.find_missing()
File "/app/home/src/download.py", line 338, in find_missing
all_downloaded = pending_handler.get_all_downloaded()
File "/app/home/src/download.py", line 221, in get_all_downloaded
all_videos = os.listdir(channel_path)
NotADirectoryError: [Errno 20] Not a directory: '/youtube/.DS_Store'`

**Comment by bbilly1** [comment]
Hmm, maybe it's a good idea to ignore all hidden files in general. This will cover many similar issues including the one that you are having. 

Thank you for bringing it to my attention, I'll look into it.

**Comment by bbilly1** [comment]
This is now merged into v0.0.4. Please update and let me know if you have any similar issues. Closing for now.
