### ISSUE TITLE
Question about populating the archive manually

### ISSUE THREAD

**Issue by akrk1986** [bbilly1/tubearchivist#32]
Looks like a great project. I was trying to use Plex Media Server to manage and share my music video collection, but Plex is not very good with music videos.

However, before I install & use it, I do have a few questions about TA (short for the tube archivist):
1. I have 15-20 YT playlists, each having 10's to 100's of videos. Is it possible to directly populate TA from a playlist?
2. I have an existing library on my hard disk - a collection of 1000's of MP4 videos - already downloaded from YT. The docs say that for each video I need to create a JSON file matching the video file. What are the contents of the JSON, or is empty?

Thanks and keep up the good work!

**Comment by bbilly1** [comment]
Hi, thanks for your interest!
1. If you look at the [getting started](https://github.com/bbilly1/tubearchivist#getting-started) you can see that you can enter playlist IDs to download. Length of the playlist doesn't matter.
2. For importing your existing collection, take a look at the [Import your existing library](https://github.com/bbilly1/tubearchivist#import-your-existing-library) part of the readme, everything should be explained there.

**Comment by akrk1986** [comment]
#1 - my bad, RTFM
#2 - can you please show an example of such a JSON file?

Thanks for the quick response!

**Comment by bbilly1** [comment]
So for the JSON file, that's for when you have backed up the original video files with the option `--write-info-json`, you can take a look at how that file is formatted when you add that option when running yt-dlp from the command line. So basically it needs to have an ID key in there, so a minimal JSON file would look something like: 
```json
{"id": "aaaaaaaaaaa"}
```

What format option have you used so far when downloading? Is the video ID somewhere the filename? Because creating the JSON files for thousands of videos or adding the id to the filename as described in the other option is going to take forever and you'd might be better off to redownload...

**Comment by akrk1986** [comment]
I assume that the ID is the value for the 'v=' parameter (https://www.youtube.com/watch?v=aaaaaaaaaa).
The reason I was asking about the manual method is for videos that I've already downloaded. But most of them are in one the playlists that I have. I download them so that I can play them offline and if a video in my playlist is that if a video is removed from YT (due to copyright), I still have an offline copy of it.
But now I realize that I may not be able to add those videos to TA since they don't have a YT ID. 
Bummer...

**Comment by bbilly1** [comment]
Yes, once it's gone it's gone, that's the point of Tube Archivist. :-)

Yes, the ID is what's after the v= parameter in the video URL. 

Having the video file is nice, you can still keep the once that you can't download again, but the metadata is as important. The biggest archive is useless if you can't find what you have archived anymore. Then just add the playlist to the download queue and it will download all available and will index everything nicely. 

OK, closing the issue for now.

**Comment by fabiosoft** [comment]
I have same big video folder...with deleted video from youtube.
Can i import with just adding the file name?

**Comment by bbilly1** [comment]
Not yet, offline import is not yet implemented: https://github.com/tubearchivist/tubearchivist/wiki/Settings#manual-media-files-import, but is on the roadmap. In any case, you will have to add the info.json file from yt-dlp to extract the metadata. Without that, there is not much you can do except using your favorite media player, for example VLC.

**Comment by fabiosoft** [comment]
Oh ok... such a shame with this amazing tool!
Thanks :)
