### ISSUE TITLE
ElasticSearch container fails to start on KDE Neon

### ISSUE THREAD

**Issue by akrk1986** [bbilly1/tubearchivist#33]
I've followed the installation instructions.
When I run (as root) 'docker-compose up', I get the error mentioned in the documentation (AccessDeniedException).
I shut down the containers and ran the command 'chown 1000:0 /mount-point', where the mount point (as I saw in the YAML file), is /usr/share/elasticsearch/data.
That directory did not exist, so created it and then set the ownership, but the problem persists.
The exception from ES also says 'refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log', but the logs directory did not exist. I created it, tried again, but the log file still does not get created.
The OS is KDE Neon (an Ubuntu derivative), docker-compose version is 1.25.0 and docker version is 20.10.7.

**Comment by bbilly1** [comment]
The mount point is on your host system, not wherever it goes into the container. Same the logs are created in the container not on your host. So you need to change the permissions on your host system where ever you have instructed docker to mount the volume.

Docker has excellent [documentation](https://docs.docker.com/storage/volumes/) about how volumes work.
