### ISSUE TITLE
Updating instructions

### ISSUE THREAD

**Issue by snowtr** [bbilly1/tubearchivist#36]
I've been running version 0.0.3 for a few days now and saw that 0.0.4 came out.  The readme file now mentions upgrade instructions by checking the docker-compose.yml file.

I did this and then used 'sudo docker-compose down' then updated my copy of the file manually (because I made changes to make it work on my system) then did 'sudo docker-compose up -d' and my ElastidSearch image updated automatically but my TubeArchivist image did not.  It still came up as version 0.0.3.  I sent it down again and then used 'sudo docker pull bbilly1/tubearchivist:latest' to get the latest one and it worked.

Not sure if it's an issue with my custom compose file, with the way docker works or if the Upgrade section of the Readme just needs updating.

Here's my custom docker-compose.yml file to confirm.

`version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    ports:
      - 8000:8000
    volumes:
      - /mnt/YouTube:/youtube
      - ./volumes/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson:latest
    container_name: archivist-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volumes/tubearchivist/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: archivist-es
    restart: always
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/tubearchivist/es:/home/itamar/elasticsearch/data
    ports:
      - 9200:9200
`

**Comment by bbilly1** [comment]
I think you are missing a `docker-compose pull` there in between, [link](https://docs.docker.com/engine/reference/commandline/pull/).

Please don't open issues that are not related to Tube Archivist. Docker is a very useful tool and absolutely worth spending the time to learn. But this project is not about learning docker, there are many useful guides and getting started write ups out there that do a much better job about teaching the basics than I ever could.
