### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by Flutter-Company** [bbilly1/tubearchivist#37]
Some videos fail with this error:
WARNING/ForkPoolWorker-8] ERROR: Postprocessing: Conversion failed!

It could be this problem: https://github.com/yt-dlp/yt-dlp/issues/871#issuecomment-911701285

Could integrating https://github.com/yt-dlp/FFmpeg-Builds resolve this issue ?

**Comment by bbilly1** [comment]
Yes, I have encountered similar issues before here. Looks like that's an limitation of ffmpeg. In the example here #26 it was a video without an audio track that broke ffmpeg. 

Did using the nightly builds link solve the issue for you? Not sure if having nightly releases of ffmpeg in the container going to solve more problems that it creates.

**Comment by tamaskan** [comment]
I used the "latest release branch 4.4" version and it was successful. Great to see the commit :-)

**Comment by bbilly1** [comment]
Nice, thanks for confirming. It will be in the next release.

**Comment by bbilly1** [comment]
is merged in v0.0.5 now, closing.
