### ISSUE TITLE
Video date and ID

### ISSUE THREAD

**Issue by geekedtv** [bbilly1/tubearchivist#38]
Is there a way to add the video date and ID to the end of the file name rather than the front of the file name? It makes manually searching more difficult when I see 20210919_2XnKoD1zCJU_ before the actual title of the video.

**Comment by bbilly1** [comment]
I currently rely on having the video ID in the filename as it is. So no there isn't really any flexibility on the naming of the files. I have been thinking about that but haven't really found a way to make that work without a drastic increase in complexity. I know that's a limitation...

**Comment by tamaskan** [comment]
@geekedtv I think you could do that with inotifywait and some script-magic ( create custom-name links in a seperate folder)
