### ISSUE TITLE
Videos wont play

### ISSUE THREAD

**Issue by Code-Slave** [bbilly1/tubearchivist#5]
Ive left all setting at default. a couple things are happening

It seems dls are stalling and i have to hit download que multiple time to get it going again. nothing helpfule in logs

when playing a video in firefox (linux) i get
no video with supported format and mimetime found.
on chrome i get no controls and or anything, just a screen with the beginning videothumnail i assume

**Comment by Code-Slave** [comment]
Is there a place for eownload worker logs etc? Im trying to see why various parts arent working for me and the docker logs really provide little detail

**Comment by bbilly1** [comment]
Take a look at the settings (gear icon) again and a the about page ('?' icon), there is more information on how the download queue works, basically you can set how many videos it will download in one go but there is currently no good way to cancel the download process. At least nothing short of killing the container, cleaning the download cache and start again. I'm aware of that limitation and have some ideas on how to improve that...

It looks like the files don't get downloaded to the correct location? Or is it a permission issue? You can follow the 404 errors in the browser console to see where the files are expected and then take a look at where they actually are. Hard to know without more information.

And yes, I'll need to implement better debugging from the worker, you can activate django debugging by passing in 'DJANGO_DEBUG=True' as an environment variable.

**Comment by Code-Slave** [comment]
That the thing. There isnt a 404 in firefox and on chrome theres no play button for the videos. Ill dig in a bit more tomorrow. Was busy with farmwork today

**Comment by bbilly1** [comment]
There won't be a 404 error on the whole page, just on the media file. Open the developer tools (Ctr+Shift+i on firefox) and you should be able to see the error in the console there.

**Comment by Code-Slave** [comment]
TTP load failed with status 403. Load of media resource http://xxx.xxx.x.xxx:8888/media/John%20Malecki/20210711_5mlwiFelQ7Y_EPIC%20Full%20Kitchen%20Renovation%20-%20Start%20to%20Finish.mp4 failed.

Thats what i get. The whole media dir permissions are 777 so its not a perm issue. Same error on every video

**Comment by bbilly1** [comment]
And where is the file located on the filesystem? Does the names match with the url? Could also be because you changed the default port from 8000 to 8888, I haven't actually tested what happens when you change the port. Just to narrow it down, can you change it to the default 8000?

**Comment by Code-Slave** [comment]
Shouldnt docker handle the port mapping? That obviously works. Is nginx only serving vids out 8000 no matter the docker settings?

**Comment by Code-Slave** [comment]
Also. To help debug it would be real nice to spool the nginx logs etc out to the config volume. Alao the sqlite db as isnt that where config is stored?

**Comment by bbilly1** [comment]
Docker handles the port mapping at the container entrance, but so far I have the 8000 port hard coded into nginx.conf that serves the media files, artwork and handles the uwsgi_pass. I'll have to look into how to make that dynamic. But the error logs are available at the default location within the container at /var/log/nginx/ if you want to take a look or export them. 

Next version, hopefully I'll be able to publish tomorrow, will show more debugging output from the worker. And will also have a media file import functionality. 

I'm closing this issue for now.

**Comment by Code-Slave** [comment]
did you fix this. 8000 is the default pot for portainer. A very highly used container. I really need to be able to change ports

**Comment by bbilly1** [comment]
no not yet.

**Comment by bbilly1** [comment]
I'm not sure what you have been trying but setting something like 8001:8000 for the port works fine for me, everything loads on 8001 without having to move the port 8000 inside the container.

**Comment by Code-Slave** [comment]
if i set mine to 8001:8000 the videos wont play. will dig into it some more

**Comment by Code-Slave** [comment]
Ok

I think I see the issue. In the docker compose. It mounts a volume
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    ports:
      - 8000:8000
    volumes:
      - ./volumes/tubearchivist/media:/youtube
      - ./volumes/tubearchivist/cache:/cache

when you go to try and play a video it looks for the video with this url

http://192.168.1.198:8888/media/731%20Woodworks/20210915_n5761aggkPo_Should%20You%20Soak%20a%20Cutting%20Board%20in%20Oil%20shorts.mp4

if i login to the the docker /media has nothing in it

if i mount /media to look the same as /youtube i still get a 403 error
