### ISSUE TITLE
Automatic Deletion of watched items after a specified time

### ISSUE THREAD

**Issue by cpt-kuesel** [bbilly1/tubearchivist#56]
Hi just stumbled across this project and first impressions are awesome.

I wanted to ask if you would consider an option to automatically delete watched videos after a week or so.
My use case is not to archive every channel but just to watch the newest videos and after that I would like to reclaim the disk space.

Let me know what you think about it.

Greetings
cpt

**Comment by bbilly1** [comment]
Hi, thanks for taking a look at Tube Archivist. Yes, I can see the use case of that. The timestamp for when you have marked the video as watched is already getting stored, so that wouldn't be too complicated to implement. 

What I'm still missing at the moment is a proper scheduler, but that's definitely something I'll have to get working anyways to do that sweet auto download and auto refresh. So it would make sense to revisit that topic again once that is accomplished. 

Thanks for your input!

**Comment by bbilly1** [comment]
OK, this is now implemented in v0.0.9. Please update!

**Comment by cpt-kuesel** [comment]
Thank you so much for implementing this feature!
I am still having some trouble getting it to work properly though.

At first I was getting FileNotFound Exceptions because I manually deleted videos before and didnt rescan the filesystem after.
That I got sorted out.
The first run after that successfully deleted 20 videos, but now whenever this runs I get this error:
`tubearchivist          | [2021-12-19 11:08:25,713: WARNING/ForkPoolWorker-4] get video data for rCdlBYUdTWQ
tubearchivist          | [2021-12-19 11:08:46,187: WARNING/ForkPoolWorker-4] auto delete older than True days
tubearchivist          | [2021-12-19 11:08:46,430: WARNING/ForkPoolWorker-4] add deleted to ignore list
tubearchivist          | [2021-12-19 11:08:46,526: WARNING/ForkPoolWorker-4] <Response [400]>
tubearchivist          | [2021-12-19 11:08:46,577: ERROR/ForkPoolWorker-4] Task download_pending[a9374e3f-1d52-4109-8de1-11d84f5d12e6] raised unexpected: ValueError('failed to add video to download queue')
tubearchivist          | Traceback (most recent call last):
tubearchivist          |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
tubearchivist          |     R = retval = fun(*args, **kwargs)
tubearchivist          |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
tubearchivist          |     return self.run(*args, **kwargs)
tubearchivist          |   File "/app/home/tasks.py", line 86, in download_pending
tubearchivist          |     downloader.run_queue()
tubearchivist          |   File "/app/home/src/download.py", line 565, in run_queue
tubearchivist          |     self.auto_delete_watched(autodelete_days)
tubearchivist          |   File "/app/home/src/download.py", line 804, in auto_delete_watched
tubearchivist          |     pending_handler.add_to_pending(all_youtube_ids, ignore=True)
tubearchivist          |   File "/app/home/src/download.py", line 98, in add_to_pending
tubearchivist          |     raise ValueError("failed to add video to download queue")
tubearchivist          | ValueError: failed to add video to download queue`
