### ISSUE TITLE
Files downloading but stopping at change of ownership (chown)

### ISSUE THREAD

**Issue by a-camacho** [bbilly1/tubearchivist#58]
Hi, the system seems to work (last version).
But my NFS mount does not allow me to chown files, only write them.

Download works, saving file in folder too. But system seems to try to change ownership and stops. After that, no other video seems to be downloaded. Is that a good reading or should that work even with that warning ?

```
[2021-10-18 09:12:48,975: ERROR/ForkPoolWorker-4] Task home.tasks.download_pending[d458a9ea-d598-48e0-b43e-d4b9bfb427a6] raised unexpected: PermissionError(1, 'Operation not permitted'),
[2021-10-18 09:12:47,024: WARNING/ForkPoolWorker-4] get video data for c6C2bh71skQ,
[2021-10-18 09:12:47,025: WARNING/ForkPoolWorker-4] ,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task,
    R = retval = fun(*args, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__,
    return self.run(*args, **kwargs),
  File "/app/home/tasks.py", line 58, in download_pending,
    downloader.run_queue(),
  File "/app/home/src/download.py", line 450, in run_queue,
    self.move_to_archive(vid_dict),
  File "/app/home/src/download.py", line 593, in move_to_archive,
    os.chown(new_file_path, host_uid, host_gid),
PermissionError: [Errno 1] Operation not permitted: '/youtube/Tchoupi/20200120_c6C2bh71skQ_Tchoupi a lecole - Papi au temps des dinosaures (S.2 EP.38).mp4'
```

Thanks a lot

**Comment by a-camacho** [comment]
Ok, it seems that commenting this line make the system work perfectly.
Could we have an option to "chown" or not the final files ?

```
os.chown(new_file_path, host_uid, host_gid)
```
to
```
#os.chown(new_file_path, host_uid, host_gid)
```

**Comment by bbilly1** [comment]
OK, this is no merged in [v0.0.7](https://github.com/bbilly1/tubearchivist/releases/tag/v0.0.7). Please give it a go.

Closing this issue.

**Comment by hafx** [comment]
I had the same issue. 
I commented the  HOST_UID and HOST_GID in the compose, and it works. 

If I didn't do that, TA was unable to download vid. (move to NFS share) 

Thanks guys.

**Comment by QuAzI** [comment]
The same story, v0.4.10 on Docker, Ubuntu 24.04
I've moved docker volumes to the external disk

/etc/fstab
```
/dev/disk/by-uuid/C68A-E7CD /media/downloads exfat defaults,auto,nofail,rw,user,umask=000 0 0
```

Volumes changed
```yaml
volumes:
  media:
    driver: local
    driver_opts:
      type: none
      device: /media/downloads/docker/volumes/tubearchivist_media
      o: bind
  cache:
    driver: local
    driver_opts:
      type: none
      device: /media/downloads/docker/volumes/tubearchivist_cache
      o: bind
  redis:
    driver: local
    driver_opts:
      type: none
      device: /media/downloads/docker/volumes/tubearchivist_redis
      o: bind
  es:
    driver: local
    driver_opts:
      type: none
      device: /media/downloads/docker/volumes/tubearchivist_es
      o: bind
```

Now, in a cycle I have:
- Downloading
- Processing
- Move downloaded to archive
- Task failed: [Errno 1] Operation not permitted: '/youtube/<channel>/<file>'

File already moved to 'media' but then fails on chown
```
[2024-10-14 16:48:34,203: ERROR/ForkPoolWorker-2] Task download_pending[8365b059-221a-4788-b98e-7ccb8dc53133] raised unexpected: PermissionError(1, 'Operation not permitted')
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/tasks.py", line 136, in download_pending
    downloaded, failed = downloader.run_queue(auto_only=auto_only)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/download/yt_dlp_handler.py", line 80, in run_queue
    self.move_to_archive(vid_dict)
  File "/app/home/src/download/yt_dlp_handler.py", line 264, in move_to_archive
    os.chown(new_path, host_uid, host_gid)
PermissionError: [Errno 1] Operation not permitted: '/youtube/UCHFl23Ah_l4gEUTXYUStQdQ/rmxRxpyYtZA.mp4'
```

And it presents in `Total videos` list all the time. Also, I can't download other videos. When I press to download any other video, first failed video starts to download again and prevent downloading of other files.

I think `chown` shouldn't fail while file saved properly
And file which already present in `media` shouldn't be downloaded again
And any way, failed video shouldn't prevent other files from downloading

**Comment by Dontkickmi22** [comment]
In your docker-compose.yml file, 
remove HOST_UID=1000 and HOST_GID=1000 (e.g. below).
Should do it.

```
cat docker-compose.yml 
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist410
    restart: unless-stopped
    image: bbilly1/tubearchivist:v0.4.10
    ports:
      - 192.168.21.10:8001:8001
    volumes:
      - /mnt/nas/downloads:/youtube
      - /media/ta:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      #- HOST_UID=1000
      #- HOST_GID=1000
.....

```

**Comment by QuAzI** [comment]
@Dontkickmi22 yeah, already did it but... why it's enabled by default, and why it goes wrong so strange, and why chown so important that can destroy everything...

**Comment by lamusmaser** [comment]
Q1. Why is this proposed by default?
A1. Because this works in most filesystems by default. This is detailed in this thread. This is only an issue with NFS, as far as we've documented.

Q2. Why it goes wrong?
A2. As detailed above, because NFS doesn't support changing the ownership of those files. This leaves all files with the overriding characteristics of the filesystem that NFS is attached to, or as the connecting user.

Q3. Why is chown important?
A3. Ensuring that the files are properly owned by the expected user is important when being accessed handled across filesystems. Very specifically, we have at least two filesystems present: the one inside the container and the host's filesystem. Making sure the host is able to access those files is important, especially when a lot of actions are being performed by root. When using an NFS mount, you are bringing in another filesystem, however the NFS protocol is going to limit the actions that can be performed, which causes these issues. When TA doesn't see the `HOST_UID` and `HOST_GID`, then it skips that step because it assumes that the owner of TA knows how to properly adjust those ownership profiles.

**Comment by QuAzI** [comment]
In my case it's not NFS, it's just non default HDD for volumes. Because no one should keep so much data on system disk.

**Comment by lamusmaser** [comment]
Oh, you're right. Similar to NFS, `exfat` has a problem with user permissions. [`exfat` does not support user permissions](https://askubuntu.com/a/923701) and would therefore run into the same problem that NFS has.
