### ISSUE TITLE
Question/Feature Request - Subtitle download & indexing

### ISSUE THREAD

**Issue by TheOneValen** [bbilly1/tubearchivist#59]
Are subtitles downloaded and indexed? Then one could search by what was said in a video.

**Comment by gonjat** [comment]
I second this feature.. My Wife like Asian Dramas and having ENG subs would be amazing. Thank you.

**Comment by dfein38347g** [comment]
Subtitles are the one killer feature I'm waiting for. I think the download client is capable. Is it possible to enable turning that "switch" on and integrate it into the search engine later?

**Comment by TheOneValen** [comment]
Thank you for your great work! Choosing the incremental approach is a good idea, all of what the feature request entailed is too big a Chunk. Should I open a follow-up issue for the search?

Is it possible to download the subtitles for existing videos?

**Comment by bbilly1** [comment]
Searching is planned, probably together with some other search improvements. It's happening at some point.

For existing videos they are downloaded with the refreshing task that's already setup. I was thinking to also put something into the *rescan filesystem* functionality as well.

**Comment by PAHXO** [comment]
Loving this feature espcially the searching!

Although, I'm not sure if there's a standard to subtitle file name format, but Jellyfin reccomends [this](https://jellyfin.org/docs/general/server/media/subtitles.html#formatting). 
Currently, TubeArchivest uses ``` "-lang.format" i.e  ("-en.vtt") ``` format instead of ``` ".lang.format" (".en.vtt)```.

**Comment by Extarys** [comment]
Offtopic:
@PAHXO Since you are mentioning Jellyfin, have you found a way to display the TubeArchivist videos in Jellyfin? I tried using a TV Series type library and it work-ish, but since all videos are in a single folder I need a lot of manual work to display them... better.

**Comment by PAHXO** [comment]
> Offtopic: @PAHXO Since you are mentioning Jellyfin, have you found a way to display the TubeArchivist videos in Jellyfin? I tried using a TV Series type library and it work-ish, but since all videos are in a single folder I need a lot of manual work to display them... better.

I just map Tube Archivist media folder to Jellyfin as 'other' and name it "YouTube". Then, each channel would have it's own sub-folder automatically, and it works just fine just no playlists support. 

Tho, for some reason when a channel is first added to  Jellyfin it would recognize it as a Series(Sometimes with multiple seasons). Then, after the download it would become a folder (which is best, I think, for now).

Note* You have to embed the metadata and thumbnails so that everything becomes a bit cleaner.

**Comment by dfein38347g** [comment]
How are the subtitles stored? I don't see them when viewing the videos in emby or jellyfin.

**Comment by bbilly1** [comment]
@dfein38347g There was an issue from yt-dlp side for auto generated subtitles, v0.1.3 has a workaround for that. subtitle files will get stored next to your video media files.
