### ISSUE TITLE
Cannot access over Firefox

### ISSUE THREAD

**Issue by MadsMighty** [bbilly1/tubearchivist#60]
I'm currently running TubeArchivist through docker on Unraid and have set up the redis and elasticsearch containers as instructed.

On Chrome I am able to access the web UI without issue, however when I try to access it through Firefox I receive the following log:

[2021-10-18 12:26:19,440: INFO/MainProcess] celery@b91bb94c1cab ready.

invalid request block size: 6559 (max 4096)...skip

invalid request block size: 6559 (max 4096)...skip

Whereas with Chrome it accepts the header and moves along. Any idea what can be done for this? I'd really rather avoid using Chrome if possible.

**Comment by bbilly1** [comment]
Hmm, any chance this has something to do with your browser configurations? Addons? Settings overwrite? My primary browser is Firefox as well, and I have never encountered that. Does that issue persist in an incognito tab? Or in a clean Firefox profile without any changes done to it?

Block size could be changed in uwsgi, but 6559 is huge, that should be a fraction of that.

**Comment by bbilly1** [comment]
OK, after some more research, I guess there is no harm in increasing the `buffer-size` to cover cases like that. Thanks for pointing it out!

**Comment by bbilly1** [comment]
OK, [v0.0.7](https://github.com/bbilly1/tubearchivist/releases/tag/v0.0.7) now has the fix merged. Closing this issue.
