### ISSUE TITLE
Playlist support in UI

### ISSUE THREAD

**Issue by gonjat** [bbilly1/tubearchivist#63]
Not sure if this has been asked yet but would a playlist view be to difficult to add in the UI? I have 1 subscribe that posts a few videos a day but uploads them in to seperate playlists... Like when I click on the person I'm subscribed to and it shows all their videos, could there be an "all" button or filter to change and then a "playlist" button? you would then need to click playlist 1 or 2 to display a list of videos in that given playlist? If not no worries.. just something I could really use. I would contribute but I'm no programmer. TIA and great program BTW!

**Comment by pairofcrocs** [comment]
> 
> 
> Not sure if this has been asked yet but would a playlist view be to difficult to add in the UI? I have 1 subscribe that posts a few videos a day but uploads them in to seperate playlists... Like when I click on the person I'm subscribed to and it shows all their videos, could there be an "all" button or filter to change and then a "playlist" button? you would then need to click playlist 1 or 2 to display a list of videos in that given playlist? If not no worries.. just something I could really use. I would contribute but I'm no programmer. TIA and great program BTW!

It's in the roadmap. I defiantly agree that this will be a great feature :)

**Comment by bbilly1** [comment]
Thanks for your input, there is a discussion thread about playlists here: #62. Let's consolidate everything regarding playlists there, so we have it all in one place. @gonjat please repost your ideas there again.
