### ISSUE TITLE
[Feature Request] Basic Auth for elasticsearch connection

### ISSUE THREAD

**Issue by TheOneValen** [bbilly1/tubearchivist#73]
Hi!

When you setup elasticsearch centrally it is recommended to setup security via basic auth.

I propose a configuration (environment variables) for basic auth username and password for connecting to an es instance.

Have a nice day!

**Comment by bbilly1** [comment]
OK, this is now merged in [v0.0.7](https://github.com/bbilly1/tubearchivist/releases/tag/v0.0.7).

**Comment by TheOneValen** [comment]
Works! Thank you. Finally got a chance to try it out and I like it. I have a lot of ideas, are feature requests the way to go here?

I have my ES instance running via https which is signed by my own PKI. I would like to provide documentation how I did that, where would I put that?

**Comment by bbilly1** [comment]
Hmm, maybe it's a good idea to have a discussion thread for "feature requests"? I have started one here at #80, let's see how this goes there.

For your ES setup, that sounds very specific for your architecture. Maybe you have a link to the official documentation of elasticsearch? Then that could be a link [here](https://github.com/bbilly1/tubearchivist#elasticsearch). Or this could also be a write up on your profile in a repo belonging to you that you maintain and then this could be linked here?

**Comment by TheOneValen** [comment]
OK, I'll look at the discussion.

Maybe you can open a section in your wiki like "Recipes" or FAQ or something like this? This is about running the tubearchivist image.
