### ISSUE TITLE
[Feature Request] Ability for custom folder and file names

### ISSUE THREAD

**Issue by ikolsteren** [bbilly1/tubearchivist#74]
The ability to change the the format of the downloaded files and folder names
I have the same files shared with Plex and the file naming needed to have some specific data in to work for the metadata agent.   I am able to modify the files names and folder after and it will work with a rescan but then new downloads break.

**Comment by bbilly1** [comment]
OK, added a little note under [Known limitations](https://github.com/bbilly1/tubearchivist#known-limitations). Something to revisit down the road.

Closing for now.
