### ISSUE TITLE
Adding Multiple Channels errors webpage 

### ISSUE THREAD

**Issue by Zyzto** [bbilly1/tubearchivist#75]
Adding multiple channels at the same time I found above 2, crash the webpage and return error 504
![image](https://user-images.githubusercontent.com/13531154/139391205-4abdcbf2-0a0c-4daf-8569-07aea0216e50.png)

while monitoring the logs site will restore after all channels are add and all thumbnails are downloaded

**Comment by bbilly1** [comment]
This is now dealt with in [v0.0.7](https://github.com/bbilly1/tubearchivist/releases/tag/v0.0.7). The user interface feedback is not ideal just yet, something that will need improving at some point.

Thanks for your input!
