### ISSUE TITLE
Cannot start with docker: AccessDeniedException[/usr/share/elasticsearch/data/nodes];

### ISSUE THREAD

**Issue by stefanorossiti** [bbilly1/tubearchivist#76]
Hi, just tried to run the docker-compose without any modification on my docker VM (ubuntu 20.04),
I am running many containers here without problem. But i can't start tubearchivist.

The container that fails to run is elasticsearch 7.15.1 causing AccessDeniedException.
This is the docker log for this container:

https://pastebin.com/ZuF7L02H

**Comment by bbilly1** [comment]
Is this the same issue as described [here](https://github.com/bbilly1/tubearchivist#permissions-for-elasticsearch)?

**Comment by stefanorossiti** [comment]
Yes. That resolved, thx.
