### ISSUE TITLE
Make password authentication optional

### ISSUE THREAD

**Issue by mindofbeholder** [bbilly1/tubearchivist#77]
Can we make user authentication optional?

My use case is that I keep tubearchivist behind an authentik reverse proxy so adding an additional layer of user password authentication is redundant.

**Comment by bbilly1** [comment]
Not sure if that is possible with django... Maybe something like a "remember me" checkbox could also work to configure the lifetime of the session? Or the SSO option you have suggested in the other thread #78 would accomplish the same.

**Comment by bbilly1** [comment]
The "remember me" checkbox is now implemented in v0.0.9.
