### ISSUE TITLE
Add sso / ldap support

### ISSUE THREAD

**Issue by mindofbeholder** [bbilly1/tubearchivist#78]
My use case is that I utilize Authentik for SSO / LDAP.

I want to be able to automatically create my users in tubearchivist when they authenticate from my authentik instance.

**Comment by bbilly1** [comment]
Yes, something to look into further down the road once the user and user roles situation is clear.

**Comment by bbilly1** [comment]
I've added it to the roadmap for now but honestly I'm not sure if and when I'll be able to look at that, as this is something I'm not using my self. If you want to get this going, please contribute!

Closing this issue for now.
