### ISSUE TITLE
Pagination for downloads page

### ISSUE THREAD

**Issue by seriousm4x** [bbilly1/tubearchivist#8]
I currently have 1000+ videos in the download queue. Requesting all the thumbnails at once from youtube slows down the page and is also too much requests I guess 😄

**Comment by bbilly1** [comment]
Yes, I can see how this will be a problem. I originally had pagination there, but found it confusing as the queue is sorted by date when you added the item. So when you add a new item, it will go to the top and you can see immediately that it worked. For the next to download, it will take the "oldest" in the list, meaning the one from the bottom. Now in your case, this will download from the bottom of page 100 or something and it might not be clear what's happening. 

But then again, that's still better than having to load 1000 thumbnails in one go... :-) So yes, I agree, there should be pagination on the download page. I'll look into it.

**Comment by bbilly1** [comment]
ok, implemented in v0.0.2. Closing.
