### ISSUE TITLE
urlopen error [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by stefanorossiti** [bbilly1/tubearchivist#84]
It worked nice for some day, but now I cannot download any video anymore. It happened after the 0.0.7 update, but I think that for a while it worked. The only other thing I did was to delete every video downloaded before. Now every download I try, fails. I use all defaults options. 
Already tried reloading the docker compose.

Here the container's log:
https://pastebin.com/CjC5W0rg

**Comment by bbilly1** [comment]
Hmm, not sure what's happening here, the video you are trying to download works fine for me, time to refresh my trigonometry knowledge. :-)

Do you see the same issue when you are trying to download the same video outside of tubearchivist from the commandline? Could it be a regional issue, is switching the vpn to another location giving the same error?

**Comment by stefanorossiti** [comment]
I don't think is a regional issue because I can see the video on YouTube. And also, it now doesn't work with any video I try even with the same videos that worked 1 week before.

How do I test if youtube-dl works? Tried using the command "youtube-dl" from within the tubearchivist container but it doenst find the program.

I just reainstalled tubearchivist delenting all volumes and gives the same error.

**Comment by bbilly1** [comment]
TubeArchivist is using yt-dlp. I mean to try to download the video outside of the container on your main system. The browser is doing more fancy stuff like cookies, so that's not a clear indicator that yt-dlp can also download it if you can play it. Maybe also try to get a new IP over a VPN, maybe you are experiencing some blocking from youtube? Your ISP? Anything in between?

 I haven't seen any issues like you are describing, I'm not sure how helpful I can be here.

**Comment by bbilly1** [comment]
@stefanorossiti Were you able to look into that? Did you find any solution?

**Comment by stefanorossiti** [comment]
Not really, I installed tube archivist on a server and installing a VPN there would require some time and effort, considering I don't have a private IP, and I'm using a tunneling service. 
However, I noticed I have the same problem with Deezer. I am in Swiss and these services shouldn't be regionally blocked. Now I am thinking at some fingerprint ban. And that YouTube is somehow detecting that something is going on from that device. (They are against downloading videos). I will definitely look into this sometime in the future, but for now is on hold. 
If you want you can close this and will open another issue later.

**Comment by bbilly1** [comment]
I have also done a little bit more research and have found widely different problem descriptions and solutions, my original hunch with that being geo dependent might not be relevant.

Maybe a reinstall of TubeArchivist will help? Delete container and image and pull fresh from docker hub? If it's fingerprinting related, this might solve that as you don't face the same issue in your local installation. 

Some of the blogposts I have read have also suggested that it's related to the kernel not releasing tcp connections in `TIME_WAIT` sate, and that it's not actually python and not youtube related. What is your server setup? OS and hardware?

**Comment by stefanorossiti** [comment]
I just ended backing up the VM and create a new slightly different one, reinstalled tubearchivist from 0. Now it works. This also fixed deezer.

It's a “nuke and rebuild” solution therefore I can't be sure I was actually figerprint banned. Maybe it was the update that messed up some file in the volume due to some non tubearchivist's code related factor. 
But one thing I am pretty sure is that the error wanted to tell me that tuberchivist couldn't connect to youtube to fetch information because he couldn't establish a network connection.

I'll pay more attention if this happens again in the future.
