### ISSUE TITLE
Issue with elasticsearch authentication - requires ssl to be enabled

### ISSUE THREAD

**Issue by KeithPetro** [bbilly1/tubearchivist#89]
I made the changes necessary to enable authentication for ES in my docker-compose file, as well as all other necessary changes, and tubearchivist just waits for elasticsearch to go up. Looking through the elasticsearch logs, I found this warning:

```archivist-es       | {"type": "server", "timestamp": "2021-11-10T21:24:52,739Z", "level": "WARN", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "6c7782ec0732", "message": "Transport SSL must be enabled if security is enabled on a [basic] license. Please set [xpack.security.transport.ssl.enabled] to [true] or disable security by setting [xpack.security.enabled] to [false]" }```

It would appear that it is necessary to setup SSL for ES in order to enable authentication. Perhaps this should be included in the setup instructions.

**Comment by bbilly1** [comment]
That shouldn't be required on a single node elastic installation. Any chance you run an older version of elasticsearch? Or how does your setup and configurations differ from the example docker-compose?

**Comment by KeithPetro** [comment]
I'm running ES 7.15.1, same as in the example docker-compose:
```version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    ports:
      - 8005:8000
    volumes:
      - /mnt/hoard_4/youtube:/youtube
      - ./volumes/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_USERNAME=user
      - TA_PASSWORD=verysecret
      - ELASTIC_PASSWORD=verysecret
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson:latest
    container_name: archivist-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./volumes/tubearchivist/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: archivist-es
    restart: always
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=verysecret"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/tubearchivist/es:/usr/share/elasticsearch/data
    expose:
      - "9200"

**Comment by bbilly1** [comment]
Hmm not sure, but I don't think that's why elasticsearch fails to start. Can you post your startup log to a pastebin somewhere?

**Comment by KeithPetro** [comment]
Unbelievably silly mistake on my part. The latest image wasn't being pulled. After pulling the latest docker image, everything is working perfectly, so I'll close this issue. Sorry for the mistake (and for taking so long to respond here, was busy the last few days).

**Comment by bbilly1** [comment]
Haha, been there, done that. I'm just happy to know that I'm not the only one doing unbelievably silly mistakes from time to time. :-)
