### ISSUE TITLE
Exposing Port 80 ?

### ISSUE THREAD

**Issue by tamaskan** [bbilly1/tubearchivist#9]
Hi, quick Question:

Why exactly is the Dockerfile exposing Port 80 when the Listener is configured on Port 8080 ?

Best regards

**Comment by bbilly1** [comment]
Yes, you are right, that should be 8000, I had it on 80 at a initial testing version and forgot to change it there. Thanks for pointing it out.

How it is setup now is that [uwsgi](https://github.com/bbilly1/tubearchivist/blob/master/uwsgi.ini) publishes the app on 8080, but that's just on localhost container internal then [nginx](https://github.com/bbilly1/tubearchivist/blob/master/nginx.conf) handles the uwsgi_pass and also serves the thumbnails and downloaded media files directly to a combined interface accessible on 8000 from outside container.

**Comment by tamaskan** [comment]
Thank you very much for the quick reply and the explanation :-)
