### ISSUE TITLE
Documentation: ES indices go read-only at 95% drive usage

### ISSUE THREAD

**Issue by sehv** [bbilly1/tubearchivist#91]
This might be a useful note to add to the wiki so it doesn't catch folks by surprise. By default, ES will effectively lock any indices on a drive when it hits 95% capacity. You can delete from indices to free up space but can't write to them. Effectively, this means no new downloads, channel subs, etc. The error that will be seen is:
"disk usage exceeded flood-stage watermark, index has read-only-allow-delete block"

This may catch users off guard, especially if they are running off a large drive, as theyll hit 95% at, for example, over half a terabyte of free space on a 14TB drive.

**Comment by bbilly1** [comment]
I find these surprisingly hard decisions to make. I mean there is the [potential pitfalls](https://github.com/bbilly1/tubearchivist#potential-pitfalls) section with problems I have encountered and multiple people mentioned they have faced and may not have an obvious solution, or at least not a solution you'd find without some researching. 

The issue you have been facing might not be obvious *why* it is an issue in the world of distributed database systems, but the solution is. When starting to add all the potential messages and errors people could face, this readme will become a troubleshooting guide for Elasticsearch which is not the goal of this project. These are also things that change constantly as Elasticsearch develops. 

So I'm not sure what's the best approach: Only have troubleshooting info for problems that have non obvious solutions? Or provide a potentially extensive and hard to navigate list, that's subjected to change and not really related to the project? Or something sensible in between? But maybe I shouldn't assume what's *obvious* from my perspective...

**Comment by sehv** [comment]
Yeah, it is a bit of a balancing act. I'd think ES-specific stuff is likely to be an uncommon skill set, most self-hosters and docker maintainers are more likely to be familiar with the foibles of mariadb and the like as the majority of FOSS docker projects tend to run those for their backends. Incidentally, a lot of the confusion, at least for me, stemmed from ES's error itself: "disk usage exceeded flood-stage watermark" sounds at first glance like it is a too-many-requests type of issue, not a disk space one.

A tradeoff might be some kind of in-band error reporting. When it gets into this state, you currently won't see any failures within the GUI. The calls return successes, but then you don't see your changes (the ignored video doesn't disappear from the list, etc). Perhaps just an error handler that catches that error and informs the user they need to check their disk usage?

**Comment by bbilly1** [comment]
Ah yes, of course, now I get it, you aren't talking about a startup error, this is a runtime error. The disk fills up wile downloading and at some point Elasticsearch just gives up without any feedback while the interface is still functional. 

At startup it's quite obvious, because there is no interface and everybody's first step will be to look at the logs to see what happened, but at runtime, there is no feedback when that happens, that's your point.

There is a health check that could be polled on an interval, or something similar. I'll do some research how this could be achieved in a general sense. Thanks for your input!

**Comment by bbilly1** [comment]
Thanks for your input, there is now a note in the email and some better error handling in v0.0.8. Closing for now.
