### ISSUE TITLE
Unable to go full-screen on mobile (iOS)

### ISSUE THREAD

**Issue by Drazzilb08** [bbilly1/tubearchivist#95]
The video name/details seem to be covering the full-screen option.
When trying to select the full-screen button the overlay comes out and "thinks" that you are selecting the "X" button.

![IMG_3971](https://user-images.githubusercontent.com/65743746/143811483-2ba073a8-0a04-41a3-bcd7-eaf2061791ef.jpeg)
As you can see here the overlay covers up the full-screen button preventing you from moving to full screen. 

Now, this only seems to be an issue on mobile. This was tested on iOS, in both Safari and Chrome.

**Comment by bbilly1** [comment]
Hmm, that's unfortunate, on every mobile browser I've tested it on, the controls and timeline are at the bottom of the video.

Thinking of it, the hover field is not really helping anyways on mobile. There needs to be a better way to have these controls, also to mark as watched. Not quite sure what's the best way to handle that but thanks for pointing it out!

**Comment by Drazzilb08** [comment]
IMO, possibly the best way on mobile is a separate button just below or a toggle switch possibly. With the video name alongside it. This idea would be similar to how it looks prior to you selecting the video. This would look similar to the big box corporation version but makes sense as well as opposed to the hover field.
![IMG_3972](https://user-images.githubusercontent.com/65743746/143892703-2df0cfdb-6629-4dcf-afee-544e06b9a22b.jpg)

**Comment by bbilly1** [comment]
Looking at your screenshot: does the interface really look that different on iOS? I mean that toggle switch is way off, and the grid/list view buttons should go to the right. I don't have access to any iOS devices...

**Comment by Drazzilb08** [comment]
To better answer, these questions here is an un-cropped version for you to see on the grid list.

![IMG_3976](https://user-images.githubusercontent.com/65743746/144063705-ccc55b13-95c9-4984-a7e8-8df866c21c2c.jpg)

To see all controls here is the view after selecting a video to be played.

![IMG_3977](https://user-images.githubusercontent.com/65743746/144063645-b6ace0e9-1ef2-40f8-bb8d-dfb422bd730a.jpg)

This is how apparently iOS handles things. This is the exact same look on both Safari and Chrome. This is also on an iPhone XS Max.

**Comment by PiotrKrzyzek** [comment]
I have this same mobile viewing experience:

I wanted to control a video while on my phone (iPhone 12 Pro max) and when I clicked the video that top 'overlay' showed and thus getting to the actual video controls was very .... difficult.

**Comment by bbilly1** [comment]
This got kind of merged together with #98. But with the new and improved video player, this shouldn't be an issue anymore. Thanks for your feedback!

**Comment by Drazzilb08** [comment]
Awesome. Thanks for the work. I'll test it out.
