### ISSUE TITLE
Feature Request: Notify users of new content.

### ISSUE THREAD

**Issue by n8detar** [bbilly1/tubearchivist#97]
The title says it all. It would be nice to have the ability to have notifications sent to users once new content is downloaded and available. Additionally, allow the users to decide which channels/playlists they want to get notifications from. Notifications could be sent by email (set up by the admin in the backend), messaging apps like Discord or Slack, or any other method really; the more options the better.

**Comment by bbilly1** [comment]
So first, I like the idea and see how this could be useful. But I don't see myself being able to maintain that, particular for services I don't use myself. I think that's beyond the scope of the project and could very well be it's own thing. 

As a matter of fact, maybe that exists already? Something like a message / notification broker? That could integrate into all these messaging platforms? Then Tube Archivist could provide the hooks and that message broker would manage all these different API integrations. 

Maybe you or somebody can look into that?

**Comment by n8detar** [comment]
> But I don't see myself being able to maintain that, particular for services I don't use myself. I think that's beyond the scope of the project and could very well be it's own thing.

That makes sense. I'm not familiar with any projects/services that do what you are suggesting, but providing an API that could be leveraged would be great because then other people can create integrations pretty easily. Maybe others know of one that's already been created and can comment here.

I know that python has a library for SMTP/SMTP SSL ([smtplib](https://docs.python.org/3/library/smtplib.html)) which is something that could also be used in addition to an API of some kind. Discord ([discord-notify](https://pypi.org/project/discord-notify/)) also has a simple library, but like you said it would get too difficult to maintain so many different notification services.

**Comment by lamusmaser** [comment]
This would probably be best by using webhooks into already established notification services (Slack, Discord, etc.) - this is what tends to be used for other media downloader services. This would then be referenced at an event's completion and would then send the message to any/all established webhooks.

**Comment by Code-Slave** [comment]
Look at a library called apprise. Lazylibrarian uses it for notifications. Support for tons of services

**Comment by bbilly1** [comment]
@Code-Slave Oh, nice! apprise looks like a very promising solution for the task.

At first glance it seems like these tokens or even full username/password will have to be stored somewhere within the application so there is a security concern that will need some attention or at least a clear warning somewhere... 

Thank you very much for the hint.

**Comment by bbilly1** [comment]
Thanks for the input, I think scope is clear and it's on the roadmap. closing this to keep the issues fresh.
