### ISSUE TITLE
Feature Request: Theater mode

### ISSUE THREAD

**Issue by PiotrKrzyzek** [bbilly1/tubearchivist#98]
Videos can be played in their regular container size or in full-screen and for most situations this is perfect. Though there are times when I would like to have a larger video and not be in full screen mode.

Here is a simple Chrome extension example of this idea: https://chrome.google.com/webstore/detail/theater-mode-for-youtube/dgognhgbpdoeidccnbfhohblklhbbomh?hl=en
Here is a more comprehensive extension which includes this idea: https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/

Would it be possible to get an option in the video player for this?

**Comment by bbilly1** [comment]
Yes, you are right, there is more space there, that's a bit wasted. Then this maybe could also fix the problems with the overlay as mentioned #95.

Any chance you can make a quick mock up how this could look like? That would be very helpful!

**Comment by PiotrKrzyzek** [comment]
Here are a few coded (via Inspect Element in Firefox) mock-ups:

Full view on a larger monitor AND zoomed out so you can see everything as an example
<img width="916" alt="Screen Shot 2021-12-02 at 4 43 30 PM" src="https://user-images.githubusercontent.com/602636/144515082-39b1e705-e7ab-4b4d-91cc-c3acdbc9895b.png">
:

Close up for top area
<img width="1704" alt="Screen Shot 2021-12-02 at 4 43 03 PM" src="https://user-images.githubusercontent.com/602636/144515113-01f1a04f-b0db-4709-ac14-908ed72c5cf3.png">
:

Close up for video scaled at meta contents below video
<img width="1704" alt="Screen Shot 2021-12-02 at 4 42 57 PM" src="https://user-images.githubusercontent.com/602636/144515187-5bbf2d4c-9391-4dd2-b736-d5a8ddcace33.png">
:

For this mock up I did the following CSS tweaks:
The <video> element itself: I changed the max-height to 90vh (70 by default)
And then the video container div: I gave that a max width of 1700px (as that is how wide my monitor's resolution is ... sort of) and then gave it a position: relative and left: -350px (or so) to align it in the more or less center.

I don't think set PX sizes would work well for this use case though, but as a mock up it was easy and quick to do.

About the mobile overlay from #95: I don't think it'll solve that problem as the issue there seems to be the interaction event on mobile and not sizing. I'll make more comments there if you'd like: though briefly to state it here: on mobile it seems that the overlay displays and prevents showing any actual video controls which ... gets frustrating; a potential easy solution is to show that overly positioned above the video container on mobile (or below) and thus not having it ON the video and thus not in the way. My apologies for discussing a different ticket on this one.

Thank you for all your hard work on this. :)

**Comment by bbilly1** [comment]
So, ok, maybe I went too far now with this, but I have been playing around:

![2021-12-06_22-10-40-screenshot](https://user-images.githubusercontent.com/35427372/144872134-6c24a21a-6ef8-456b-8449-0ee52817e429.png)

That screenshot shows the player window with 100vh and the video embedded within.

So theater mode, or distraction less mode, or whatever you want to call it, have the title linking to the video page and channel name linking to the channel page below, same for the controls, mark as watched, and close the player all in one view. 

So the \#player tag link (when you click on the play icon) will focus to the player window as show in the screenshot but you can still scroll up and down to the rest of the page. 

With some more tweaking for mobile this will conveniently save issue #95 as well.

Theater mode could also made optional in the settings but I think I like it so far. Thoughts? Any chance you'd like to build the image from latest testing branch and give it a run in your testing environment?

**Comment by bbilly1** [comment]
Is now published in v0.0.9. Can be extended with more controls like *next* in the playlist and more. Thanks for your input!
