### ISSUE TITLE
Invalid syntax error on version check file

### ISSUE THREAD

**Issue by cinetube** [bbilly1/tubearchivist#99]
![Screenshot 2021-12-05 231047](https://user-images.githubusercontent.com/23441775/144756334-c0d69017-824a-48f2-a6c9-1b3cd580512b.jpg)

I am trying to install Tube Archivist using "deploy.sh" file and getting the above mentioned syntax error. How to resolve this issue?

Installed python version 

2.7.18
3.9.7

**Comment by bbilly1** [comment]
I'm pretty sure this runs that script in an old python version, so setup your environment to default to python 3 or change the bang to point to your desired python version or specify which python version you want to lunch that script in. You could also skip that version check if you want to. 

Also take a look at the contributing page for more details on how to build the image. There are also additional useful comments in the script too. 

That deploy.sh is to easily test your changes in your testing environment and might not be universally usable. You might need to customize it to fit your environment.
